"""The one place the factory touches an agent, exercised against a real process.

D-018 makes the adapter a narrow seam — launch, monitor, terminate, classify,
archive — and every property US2 asks of it is only observable *from inside the
child*: which environment variables survived the allowlist, which directory the
agent ran in, what arrived on stdin, whether SIGTERM reached the whole process
group. So these tests launch `tests/stub_agent.py` as the agent CLI and read back
what it recorded. A fake process object would assert only that the fake agrees
with itself.

Four properties are what this file actually defends:

- **The child environment is an allowlist, not a scrub** (US2-S1). Every test
  here runs with `LITELLM_MASTER_KEY` and `TELEGRAM_BOT_TOKEN` planted in the
  worker environment, because the guarantee is that the agent's environment is
  *built*, not *filtered*: the master key is absent by construction, along with
  the credential the worker host acquires next quarter. The per-attempt virtual
  key is the only credential allowed through (constitution V), and it arrives as
  `ANTHROPIC_AUTH_TOKEN` — the bearer-token path the proxy expects (R6).

- **A deadline ends the process tree, not just the process** (US2-S3). An agent
  spawns `git`, `uv`, test runners; killing only its root leaves grandchildren
  holding the worktree. The stub is scripted to ignore SIGTERM and to spawn a
  child of its own, so "TERM the group, then KILL what survives" is *observed*
  rather than assumed — the stub's own signal log shows the TERM, and only the
  KILL can have ended a run that ignored it.

- **Nothing semantic is read** (FR-012). Classification is exit-status only:
  zero → COMPLETED, non-zero → AGENT_ERROR, deadline → TIMEOUT. The stub prints
  to stdout and stderr in several tests and none of it reaches the result — the
  log is evidence, never an input to a decision.

- **Evidence survives every path** (FR-007, US2-S4). The attempt directory holds
  `stdout.log` and the session transcript whether the agent exited cleanly,
  failed, or was killed mid-run — the killed case being the one where a partial
  transcript is the only account of what happened. It lives under the worker
  host's `.factory/`, never inside a repo worktree, where salvage would commit it.

Two deliberate choices in the setup:

- **The worktree is a plain directory.** The adapter's contract is "cwd is the
  path you were handed"; it runs no git and would not notice a repository. Using
  a real checkout here would imply a dependency that does not exist —
  `tests/test_worktree.py` owns the git half.

- **Timeouts and grace periods are small.** `timeout_s=1` with a sub-second
  grace keeps the deadline tests honest and fast; the production values are the
  persona registry's (FR-010) and are nobody's business here.

Written before `factory/workgraph/adapter.py` exists (T012 precedes T013): until
the module lands, every test here fails at import.
"""

from __future__ import annotations

import asyncio
import contextlib
import json
import os
import signal
import subprocess
import sys
import time
from pathlib import Path
from typing import Any, Callable, Iterator

import pytest

from factory.usage.models import Termination
from factory.workgraph.adapter import (
    STDOUT_LOG_NAME,
    AdapterError,
    ClaudeCodeAdapter,
    adapter_for,
    attempt_env,
    pid_file,
    transcript_dir,
)
from factory.workgraph.models import AdapterResult, AttemptContext
from tests.stub_agent import (
    BANNER,
    STUB_AGENT_PATH,
    TRANSCRIPT_END,
    TRANSCRIPT_START,
    install_as,
    last_invocation,
    session_transcript_path,
    write_control,
)

EPIC = "003-merge-queue"
NODE = "us1"

#: Not 1: the attempt number names the archive directory, and an off-by-one that
#: always wrote `attempt-1` would pass every test that only ever ran one attempt.
ATTEMPT = 2

#: Generated by the workflow with `workflow.uuid4()` (R6) — the adapter passes it
#: through and finds the transcript by it, so a fixed value is exactly right here.
SESSION_ID = "6b1f5d4e-3a2c-4f80-9c1a-7e6d5b4a3c21"

#: A LiteLLM alias as `personas.yaml` writes them. The adapter never interprets
#: it; it travels from the registry to argv (constitution VII).
MODEL_ALIAS = "anthropic/CHANGEME"

PROXY_URL = "http://litellm.test:4000"
VIRTUAL_KEY = "sk-virtual-003-merge-queue-us1-2"

#: Planted in the worker environment by `worker_env` below, and absent from every
#: child this file launches. Distinctive strings so a leak is greppable.
MASTER_KEY = "sk-master-must-never-reach-an-agent"
BOT_TOKEN = "1234567:telegram-bot-token-must-never-reach-an-agent"

PROMPT = (
    "You are the implementer persona.\n\n"
    "## Scope\n\nImplement US1 of specs/003-merge-queue.\n"
    "Non-ASCII survives the pipe: — ✅ ✂\n"
)

#: Long enough that no test races its own deadline, short enough that a hung
#: adapter fails the suite rather than holding it open.
GENEROUS_TIMEOUT_S = 60

#: The deadline tests' bound, and the gap between TERM and KILL. Both small so
#: the escalation is observable in about a second and a half.
DEADLINE_S = 1
TEST_GRACE_S = 0.4

#: Ceiling for "the adapter is not wedged" assertions.
PATIENCE_S = 20.0


# --- setup -------------------------------------------------------------------


@pytest.fixture(autouse=True)
def fake_home(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """`HOME` for both sides: the stub reads its control file here, and writes
    its session transcript under `.claude/projects/` here, which is where the
    adapter has to look for it (R6).

    Autouse because a test that forgot it would read the operator's real home —
    scripting the stub through whatever `~/stub-agent-control.json` happened to
    be lying around, and archiving from a real Claude Code history.
    """
    home = tmp_path / "home"
    home.mkdir()
    monkeypatch.setenv("HOME", str(home))
    return home


@pytest.fixture(autouse=True)
def worker_env(monkeypatch: pytest.MonkeyPatch) -> None:
    """A worker host's environment: credentials, locale, and ordinary clutter.

    The credentials are planted for every test in this file, not just the one
    that names them — the allowlist's promise is that no launch anywhere can
    carry them, and a fixture that only appeared in the leak test would leave
    every other path unwatched.
    """
    monkeypatch.setenv("LITELLM_MASTER_KEY", MASTER_KEY)
    monkeypatch.setenv("TELEGRAM_BOT_TOKEN", BOT_TOKEN)
    monkeypatch.setenv("LITELLM_PROXY_URL", "http://litellm.test:4000")
    monkeypatch.setenv("LANG", "en_US.UTF-8")
    monkeypatch.setenv("TERM", "dumb")
    # Not a credential and still not the agent's business: the allowlist is
    # closed, so an ordinary variable is dropped exactly like a secret.
    monkeypatch.setenv("EDITOR", "vim")


@pytest.fixture
def worktree(tmp_path: Path) -> Path:
    """Where the agent runs. A directory, not a repository — see the docstring."""
    path = tmp_path / "worktrees" / EPIC / NODE
    path.mkdir(parents=True)
    return path


@pytest.fixture
def factory_root(tmp_path: Path) -> Path:
    """The worker host's state directory: transcripts, pid files (plan.md)."""
    return tmp_path / ".factory"


@pytest.fixture
def attempt(worktree: Path) -> Callable[..., AttemptContext]:
    """Build the attempt's context; `attempt(timeout_s=1)` overrides one field."""

    def build(**overrides: Any) -> AttemptContext:
        fields: dict[str, Any] = {
            "epic_id": EPIC,
            "node_id": NODE,
            "attempt": ATTEMPT,
            "prompt": PROMPT,
            "worktree_path": str(worktree),
            "proxy_url": PROXY_URL,
            "virtual_key": VIRTUAL_KEY,
            "model_alias": MODEL_ALIAS,
            "session_id": SESSION_ID,
            "timeout_s": GENEROUS_TIMEOUT_S,
        }
        return AttemptContext(**(fields | overrides))

    return build


@pytest.fixture
def adapter() -> ClaudeCodeAdapter:
    """The real adapter, pointed at the stub instead of `claude`."""
    return ClaudeCodeAdapter(executable=str(STUB_AGENT_PATH), grace_s=TEST_GRACE_S)


@pytest.fixture
def spawn_orphan() -> Iterator[Callable[[], subprocess.Popen[bytes]]]:
    """Start a process in its own session — an agent the worker host forgot (R4).

    Its own session makes its pid its process-group id, which is what a pid file
    from a crashed worker names. Anything still alive at teardown is killed, so a
    failing assertion cannot leave a sleeper behind.
    """
    spawned: list[subprocess.Popen[bytes]] = []

    def spawn() -> subprocess.Popen[bytes]:
        process = subprocess.Popen(
            [sys.executable, "-c", "import time; time.sleep(300)"],
            stdin=subprocess.DEVNULL,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            start_new_session=True,
        )
        spawned.append(process)
        return process

    yield spawn

    for process in spawned:
        if process.poll() is None:
            process.kill()
        with contextlib.suppress(subprocess.TimeoutExpired):
            process.wait(timeout=PATIENCE_S)


# --- helpers -----------------------------------------------------------------


async def wait_until(
    predicate: Callable[[], bool], *, what: str, timeout_s: float = PATIENCE_S
) -> None:
    """Poll `predicate` until it holds, or fail naming what never happened."""
    deadline = time.monotonic() + timeout_s
    while time.monotonic() < deadline:
        if predicate():
            return
        await asyncio.sleep(0.02)
    raise AssertionError(f"timed out after {timeout_s}s waiting for {what}")


def stub_is_up(worktree: Path) -> bool:
    """Whether a launched stub has finished recording itself.

    Keyed on the stdin record because the stub writes it last, once the prompt is
    drained: by then argv, env, cwd and the process ids are all on disk.
    """
    return bool(list(worktree.glob(".stub-agent/*/stdin.txt")))


def plant_pid_file(factory_root: Path, contents: str) -> Path:
    """Leave `.factory/run/<epic>/<node>.pid` behind, as a dead worker would."""
    path = pid_file(factory_root, EPIC, NODE)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(contents, encoding="utf-8")
    return path


def pid_alive(pid: int) -> bool:
    """Whether signal 0 still finds `pid` (a zombie counts as alive — it exists)."""
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        return True
    return True


def archive_dir(factory_root: Path, attempt_number: int = ATTEMPT) -> Path:
    return transcript_dir(factory_root, EPIC, NODE, attempt_number)


def stdout_log(factory_root: Path, attempt_number: int = ATTEMPT) -> str:
    return (archive_dir(factory_root, attempt_number) / STDOUT_LOG_NAME).read_text(
        encoding="utf-8"
    )


def archived_transcript_events(factory_root: Path, attempt_number: int = ATTEMPT) -> list[str]:
    """The `event` field of each record in the archived session transcript.

    `["start"]` alone is a run that was killed between the two writes — the
    partial evidence FR-007 exists to keep.
    """
    path = archive_dir(factory_root, attempt_number) / f"{SESSION_ID}.jsonl"
    lines = path.read_text(encoding="utf-8").splitlines()
    return [json.loads(line)["event"] for line in lines if line.strip()]


# --- the seam (D-018) ---------------------------------------------------------


def test_the_registrys_agent_field_names_the_adapter() -> None:
    """A persona says `agent: claude-code`; that string resolves to the class."""
    resolved = adapter_for("claude-code")

    assert isinstance(resolved, ClaudeCodeAdapter)
    assert resolved.name == "claude-code"


def test_an_unknown_agent_names_itself_in_the_error() -> None:
    """A second agent is a second class (D-018) — until then, say which is missing."""
    with pytest.raises(AdapterError) as raised:
        adapter_for("opencode")

    assert "opencode" in str(raised.value)


# --- launch: environment (US2-S1) ---------------------------------------------


async def test_the_child_environment_is_exactly_the_allowlist(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    fake_home: Path,
) -> None:
    """Six variables, no more: the table in contracts/adapter.md § Environment."""
    write_control(fake_home)

    await adapter.run_attempt(attempt(), factory_root=factory_root)

    env = last_invocation(worktree).env
    assert set(env) == {
        "ANTHROPIC_BASE_URL",
        "ANTHROPIC_AUTH_TOKEN",
        "PATH",
        "HOME",
        "LANG",
        "TERM",
    }
    assert env["ANTHROPIC_BASE_URL"] == PROXY_URL
    assert env["ANTHROPIC_AUTH_TOKEN"] == VIRTUAL_KEY
    assert env["PATH"] == os.environ["PATH"]
    assert env["HOME"] == str(fake_home)
    assert env["LANG"] == "en_US.UTF-8"
    assert env["TERM"] == "dumb"


async def test_no_worker_credential_reaches_the_agent(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    fake_home: Path,
) -> None:
    """US2-S1: never the master key or the bot token — by omission, not redaction.

    The values are checked as well as the names: a "scrubbed" environment that
    smuggled the master key through under `ANTHROPIC_AUTH_TOKEN` would satisfy a
    name-only assertion and hand an agent the keys to the proxy.
    """
    write_control(fake_home)

    await adapter.run_attempt(attempt(), factory_root=factory_root)

    env = last_invocation(worktree).env
    assert "LITELLM_MASTER_KEY" not in env
    assert "TELEGRAM_BOT_TOKEN" not in env
    assert "LITELLM_PROXY_URL" not in env
    assert "EDITOR" not in env
    assert MASTER_KEY not in env.values()
    assert BOT_TOKEN not in env.values()


def test_attempt_env_omits_a_passthrough_the_worker_does_not_set(
    attempt: Callable[..., AttemptContext],
) -> None:
    """The pure builder: passthrough is passthrough, not invention.

    A worker without `LANG` gives a child without `LANG` — an empty string here
    would be the factory asserting a locale nobody configured.
    """
    env = attempt_env(
        attempt(),
        {"PATH": "/usr/bin:/bin", "HOME": "/home/worker", "LITELLM_MASTER_KEY": MASTER_KEY},
    )

    assert env == {
        "ANTHROPIC_BASE_URL": PROXY_URL,
        "ANTHROPIC_AUTH_TOKEN": VIRTUAL_KEY,
        "PATH": "/usr/bin:/bin",
        "HOME": "/home/worker",
    }


# --- launch: the invocation (US2-S1, R6) --------------------------------------


async def test_the_prompt_arrives_on_stdin_verbatim(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    fake_home: Path,
) -> None:
    """stdin, not argv: assembled prompts run to hundreds of KB (ARG_MAX, R6).

    That the stub returns at all is half the assertion — an adapter that wrote
    the prompt without closing the pipe would leave it blocked in `read()` until
    the deadline.
    """
    write_control(fake_home)

    await adapter.run_attempt(attempt(), factory_root=factory_root)

    assert last_invocation(worktree).stdin == PROMPT


async def test_the_agent_runs_in_the_nodes_worktree(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    fake_home: Path,
) -> None:
    """FR-013's isolation is a cwd: the agent sees its node's tree and nothing else."""
    write_control(fake_home)

    await adapter.run_attempt(attempt(), factory_root=factory_root)

    assert Path(last_invocation(worktree).cwd) == worktree.resolve()


async def test_argv_carries_the_model_alias_and_the_generated_session_id(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    fake_home: Path,
) -> None:
    """`claude -p --dangerously-skip-permissions --model <alias> --session-id <uuid>`.

    The alias travels from the persona registry through argv — the adapter names
    no model (constitution VII) — and the session id is what makes the transcript
    discoverable afterwards (R6).
    """
    write_control(fake_home)

    await adapter.run_attempt(attempt(), factory_root=factory_root)

    argv = last_invocation(worktree).argv
    assert "-p" in argv
    assert "--dangerously-skip-permissions" in argv
    assert last_invocation(worktree).flag("--model") == MODEL_ALIAS
    assert last_invocation(worktree).flag("--session-id") == SESSION_ID


async def test_the_default_executable_is_claude_found_on_the_childs_path(
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    fake_home: Path,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Nothing configures the binary: `claude` is resolved from the passed-through
    `PATH`, which is the only reason passing `PATH` through matters at all."""
    bin_dir = tmp_path / "bin"
    install_as(bin_dir, "claude")
    monkeypatch.setenv("PATH", f"{bin_dir}{os.pathsep}{os.environ['PATH']}")
    write_control(fake_home)

    result = await ClaudeCodeAdapter(grace_s=TEST_GRACE_S).run_attempt(
        attempt(), factory_root=factory_root
    )

    assert result.termination == Termination.COMPLETED
    assert Path(last_invocation(worktree).argv[0]).name == "claude"


# --- classification (US2-S2) ---------------------------------------------------


async def test_a_clean_exit_is_completed(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    factory_root: Path,
    fake_home: Path,
) -> None:
    """Exit 0 is the whole of the signal — COMPLETED is a process fact, not a
    claim of success (FR-012). The verdict comes from 002, later."""
    write_control(fake_home, exit_code=0, stdout="I have completed the task.")

    result = await adapter.run_attempt(attempt(), factory_root=factory_root)

    assert isinstance(result, AdapterResult)
    assert result.termination == Termination.COMPLETED


async def test_a_non_zero_exit_is_an_agent_error(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    factory_root: Path,
    fake_home: Path,
) -> None:
    """Any non-zero code, unexamined: the exit status is not a diagnosis."""
    write_control(fake_home, exit_code=3, stderr="context window exceeded")

    result = await adapter.run_attempt(attempt(), factory_root=factory_root)

    assert result.termination == Termination.AGENT_ERROR


async def test_agent_output_never_reaches_the_result(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    factory_root: Path,
    fake_home: Path,
) -> None:
    """FR-012: an agent that declares failure while exiting 0 still terminates
    COMPLETED, and the log holds the words the result does not."""
    write_control(
        fake_home, exit_code=0, stdout="FAILED: I could not do it", stderr="ERROR ERROR"
    )

    result = await adapter.run_attempt(attempt(), factory_root=factory_root)

    assert result.termination == Termination.COMPLETED
    log = stdout_log(factory_root)
    assert "FAILED: I could not do it" in log
    # stderr is merged into the one log: interleaved as the agent wrote it.
    assert "ERROR ERROR" in log


# --- the deadline (US2-S3) -----------------------------------------------------


async def test_a_run_that_outlives_its_deadline_is_terminated_and_classified_timeout(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    fake_home: Path,
) -> None:
    """TERM to the group, grace, then KILL — enforced in-activity, not by Temporal.

    The stub ignores SIGTERM and spawns a child of its own, so both halves are
    observable: its signal log records the TERM it survived, and the grandchild —
    reachable only through the process *group* — is gone by the end. A run that
    ignored TERM and still ended can only have ended on KILL.
    """
    write_control(
        fake_home, sleep_s=300.0, ignore_sigterm=True, spawn_child=True, child_sleep_s=300.0
    )
    started = time.monotonic()

    result = await adapter.run_attempt(
        attempt(timeout_s=DEADLINE_S), factory_root=factory_root
    )
    elapsed = time.monotonic() - started

    assert result.termination == Termination.TIMEOUT
    assert elapsed < PATIENCE_S, "the deadline was not enforced in-activity"

    invocation = last_invocation(worktree)
    assert any(entry.startswith("TERM") for entry in invocation.signals)

    grandchild = invocation.child_pid
    assert grandchild is not None
    await wait_until(
        lambda: not pid_alive(grandchild), what="the agent's child to be killed too"
    )


async def test_a_deadline_leaves_the_evidence_the_run_produced(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    factory_root: Path,
    fake_home: Path,
) -> None:
    """FR-007 on the killed path: a partial transcript is the only account there is.

    The stub writes its `start` record before sleeping and its `end` record after,
    so an archive holding `start` alone is proof that what existed at the moment
    of death was kept — not that a tidy run was copied afterwards.
    """
    write_control(fake_home, sleep_s=300.0, stdout="working on it")

    result = await adapter.run_attempt(
        attempt(timeout_s=DEADLINE_S), factory_root=factory_root
    )

    assert result.termination == Termination.TIMEOUT
    assert Path(result.transcript_path) == archive_dir(factory_root)
    assert "working on it" in stdout_log(factory_root)
    assert archived_transcript_events(factory_root) == [TRANSCRIPT_START]


# --- the archive (US2-S4, FR-007) ----------------------------------------------


async def test_the_attempt_directory_holds_the_log_and_the_session_transcript(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    factory_root: Path,
    fake_home: Path,
    worktree: Path,
) -> None:
    """`.factory/transcripts/<epic>/<node>/attempt-<n>/`, keyed by attribution."""
    write_control(fake_home)

    result = await adapter.run_attempt(attempt(), factory_root=factory_root)

    expected = factory_root / "transcripts" / EPIC / NODE / f"attempt-{ATTEMPT}"
    assert Path(result.transcript_path) == expected
    assert expected.is_dir()

    assert BANNER in (expected / STDOUT_LOG_NAME).read_text(encoding="utf-8")

    # A copy, not a move: the session file the agent wrote is still where it was,
    # and the archived bytes are the same bytes.
    source = session_transcript_path(fake_home, worktree, SESSION_ID)
    assert source.is_file()
    assert (expected / f"{SESSION_ID}.jsonl").read_bytes() == source.read_bytes()
    assert archived_transcript_events(factory_root) == [TRANSCRIPT_START, TRANSCRIPT_END]


async def test_an_agent_that_wrote_no_transcript_still_archives_its_output(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    factory_root: Path,
    fake_home: Path,
) -> None:
    """A missing session file is not a missing archive: the log is still evidence,
    and a crash on the archive step would cost the attempt its whole record."""
    write_control(fake_home, write_transcript=False, exit_code=1)

    result = await adapter.run_attempt(attempt(), factory_root=factory_root)

    assert result.termination == Termination.AGENT_ERROR
    assert Path(result.transcript_path) == archive_dir(factory_root)
    assert BANNER in stdout_log(factory_root)
    assert not (archive_dir(factory_root) / f"{SESSION_ID}.jsonl").exists()


async def test_each_attempt_archives_under_its_own_number(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    factory_root: Path,
    fake_home: Path,
) -> None:
    """Retries share the worktree (FR-013) and must not share the record: the
    prior attempt's evidence is what a retry prompt quotes (FR-006)."""
    write_control(fake_home, stdout="first")
    first = await adapter.run_attempt(attempt(attempt=1), factory_root=factory_root)

    write_control(fake_home, stdout="second")
    second = await adapter.run_attempt(attempt(attempt=2), factory_root=factory_root)

    assert first.transcript_path != second.transcript_path
    assert "first" in stdout_log(factory_root, 1)
    assert "second" in stdout_log(factory_root, 2)
    assert "second" not in stdout_log(factory_root, 1)


async def test_transcripts_never_land_inside_the_worktree(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    factory_root: Path,
    fake_home: Path,
    worktree: Path,
) -> None:
    """FR-007: they stay on the worker host. Inside the tree, salvage would commit
    the agent's own transcript to the node branch and the diff check would read it
    as work."""
    write_control(fake_home)

    result = await adapter.run_attempt(attempt(), factory_root=factory_root)

    archive = Path(result.transcript_path).resolve()
    assert not archive.is_relative_to(worktree.resolve())
    assert not list(worktree.rglob(STDOUT_LOG_NAME))
    assert not list(worktree.rglob("*.jsonl"))


# --- reaping an orphan (R4) ----------------------------------------------------


async def test_a_live_process_group_from_a_previous_run_is_reaped_before_relaunch(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    fake_home: Path,
    spawn_orphan: Callable[[], subprocess.Popen[bytes]],
) -> None:
    """The worker died mid-attempt; Temporal retried; the old agent is still there.

    Two agents in one worktree is corruption, so the check is *before* the launch
    — asserted by looking at the orphan the moment the new stub reports itself up,
    not merely at the end of the run.
    """
    orphan = spawn_orphan()
    plant_pid_file(factory_root, f"{orphan.pid}\n")
    write_control(fake_home, sleep_s=2.0)

    run = asyncio.create_task(adapter.run_attempt(attempt(), factory_root=factory_root))
    try:
        await wait_until(lambda: stub_is_up(worktree), what="the new agent to launch")
        assert orphan.poll() is not None, "the orphan was still alive at relaunch"
    finally:
        result = await run

    assert result.termination == Termination.COMPLETED
    assert orphan.wait(timeout=PATIENCE_S) in (-signal.SIGTERM, -signal.SIGKILL)


async def test_the_pid_file_names_this_attempts_group_and_is_removed_on_exit(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    fake_home: Path,
) -> None:
    """The file is the next run's only handle on this one (R4), so it names the
    process *group* — the agent's children are what have to die with it — and it
    goes away on a clean exit, because a stale pid is a reap of somebody else."""
    write_control(fake_home, sleep_s=2.0)
    path = pid_file(factory_root, EPIC, NODE)

    run = asyncio.create_task(adapter.run_attempt(attempt(), factory_root=factory_root))
    try:
        await wait_until(lambda: stub_is_up(worktree), what="the agent to launch")
        assert path.is_file()
        assert int(path.read_text(encoding="utf-8").strip()) == last_invocation(worktree).pgid
    finally:
        await run

    assert not path.exists()


@pytest.mark.parametrize(
    "planted",
    [
        pytest.param("", id="empty"),
        pytest.param("not-a-pid\n", id="garbage"),
        # A worker killed mid-write can leave anything here, and `killpg(0, …)`
        # means "this process group" — the worker's own. It must never be sent.
        pytest.param("0\n", id="zero"),
    ],
)
async def test_an_unusable_pid_file_is_not_an_error(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    factory_root: Path,
    fake_home: Path,
    planted: str,
) -> None:
    """Reaping is a precaution, not a gate: garbage from a crashed worker must not
    cost the node its attempt."""
    plant_pid_file(factory_root, planted)
    write_control(fake_home)

    result = await adapter.run_attempt(attempt(), factory_root=factory_root)

    assert result.termination == Termination.COMPLETED


async def test_a_pid_file_naming_a_dead_process_is_not_an_error(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    factory_root: Path,
    fake_home: Path,
    spawn_orphan: Callable[[], subprocess.Popen[bytes]],
) -> None:
    """The ordinary case: the previous attempt exited but never got to tidy up."""
    departed = spawn_orphan()
    departed.kill()
    departed.wait(timeout=PATIENCE_S)
    plant_pid_file(factory_root, f"{departed.pid}\n")
    write_control(fake_home)

    result = await adapter.run_attempt(attempt(), factory_root=factory_root)

    assert result.termination == Termination.COMPLETED


# --- monitoring (R2) -----------------------------------------------------------


async def test_the_adapter_beats_while_it_waits(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    factory_root: Path,
    fake_home: Path,
) -> None:
    """The heartbeat is a callback, not an import of Temporal: the activity passes
    `activity.heartbeat`, which is what makes an hours-long attempt cancellable
    and a dead worker detectable in minutes rather than at the deadline (R2)."""
    beats: list[int] = []
    write_control(fake_home, sleep_s=1.0)

    result = await adapter.run_attempt(
        attempt(),
        factory_root=factory_root,
        heartbeat=lambda: beats.append(1),
        heartbeat_interval_s=0.05,
    )

    assert result.termination == Termination.COMPLETED
    assert len(beats) >= 3, f"expected repeated beats over a 1s run, got {len(beats)}"
