"""The one place the factory touches an agent, exercised against a real process.

D-018 makes the adapter a narrow seam — launch, monitor, terminate, classify,
archive — and every property US2 asks of it is only observable *from inside the
child*: which environment variables survived the allowlist, which directory the
agent ran in, what arrived on stdin, whether SIGTERM reached the whole process
group. So these tests launch `tests/stub_agent.py` as the agent CLI and read back
what it recorded. A fake process object would assert only that the fake agrees
with itself.

Four properties are what this file actually defends:

- **The child environment is an allowlist, not a scrub** (US2-S1). Every test
  here runs with `LITELLM_MASTER_KEY` and `TELEGRAM_BOT_TOKEN` planted in the
  worker environment, because the guarantee is that the agent's environment is
  *built*, not *filtered*: the master key is absent by construction, along with
  the credential the worker host acquires next quarter. The per-attempt virtual
  key is the only credential allowed through (constitution V), and it arrives as
  `ANTHROPIC_AUTH_TOKEN` — the bearer-token path the proxy expects (R6).

- **A deadline ends the process tree, not just the process** (US2-S3). An agent
  spawns `git`, `uv`, test runners; killing only its root leaves grandchildren
  holding the worktree. The stub is scripted to ignore SIGTERM and to spawn a
  child of its own, so "TERM the group, then KILL what survives" is *observed*
  rather than assumed — the stub's own signal log shows the TERM, and only the
  KILL can have ended a run that ignored it.

- **Nothing semantic is read** (FR-012). Classification is exit-status only:
  zero → COMPLETED, non-zero → AGENT_ERROR, deadline → TIMEOUT. The stub prints
  to stdout and stderr in several tests and none of it reaches the result — the
  log is evidence, never an input to a decision.

- **Evidence survives every path** (FR-007, US2-S4). The attempt directory holds
  `stdout.log` and the session transcript whether the agent exited cleanly,
  failed, or was killed mid-run — the killed case being the one where a partial
  transcript is the only account of what happened. It lives under the worker
  host's `.factory/`, never inside a repo worktree, where salvage would commit it.

- **The home the factory owns is the only home the agent sees** (US1/US2). The
  adapter seeds that home from its own constants so the CLI starts without
  prompting and so the agent's own git commits carry the factory's identity,
  never the operator's (FR-004, FR-005).

Two deliberate choices in the setup:

- **The worktree is a plain directory.** The adapter's contract is "cwd is the
  path you were handed"; it runs no git and would not notice a repository. Using
  a real checkout here would imply a dependency that does not exist —
  `tests/test_worktree.py` owns the git half.

- **Timeouts and grace periods are small.** `timeout_s=1` with a sub-second
  grace keeps the deadline tests honest and fast; the production values are the
  persona registry's (FR-010) and are nobody's business here.

Written before `factory/workgraph/adapter.py` exists (T012 precedes T013): until
the module lands, every test here fails at import.
"""

from __future__ import annotations

import asyncio
import contextlib
import inspect
import json
import os
import signal
import subprocess
import sys
import time
from pathlib import Path
from typing import Any, Callable, Iterator, Mapping, Optional

import pytest
from temporalio.converter import DataConverter

from factory.usage.models import Termination, UsageSnapshot
from factory.workgraph.adapter import (
    STDOUT_LOG_NAME,
    AdapterError,
    AgentAdapter,
    ClaudeCodeAdapter,
    CredentialStage,
    HostAgentBackend,
    SharedAttemptPolicy,
    _ADAPTERS,
    _feed_prompt,
    adapter_for,
    attempt_env,
    home_path,
    pid_file,
    transcript_dir,
)
from factory.workgraph.models import AdapterResult, AttemptContext
from factory.workgraph.worktree import (
    SALVAGE_AUTHOR_EMAIL,
    SALVAGE_AUTHOR_NAME,
)
from tests.stub_agent import (
    ATTEMPT_ARCHIVE_ENV,
    BANNER,
    FERRY_ANSWER_FILE,
    FERRY_QUESTION_FILE,
    STUB_AGENT_PATH,
    TRANSCRIPT_END,
    TRANSCRIPT_START,
    UNRECOGNIZED_MODEL_WARNING,
    install_as,
    last_invocation,
    session_transcript_path,
    write_control,
)

EPIC = "003-merge-queue"
NODE = "us1"

#: Not 1: the attempt number names the archive directory, and an off-by-one that
#: always wrote `attempt-1` would pass every test that only ever ran one attempt.
ATTEMPT = 2

#: Generated by the workflow with `workflow.uuid4()` (R6) — the adapter passes it
#: through and finds the transcript by it, so a fixed value is exactly right here.
SESSION_ID = "6b1f5d4e-3a2c-4f80-9c1a-7e6d5b4a3c21"

#: A LiteLLM alias as `personas.yaml` writes them. The adapter never interprets
#: it; it travels from the registry to argv (constitution VII).
MODEL_ALIAS = "anthropic/CHANGEME"

PROXY_URL = "http://litellm.test:4000"
VIRTUAL_KEY = "sk-virtual-003-merge-queue-us1-2"

#: Planted in the worker environment by `worker_env` below, and absent from every
#: child this file launches. Distinctive strings so a leak is greppable.
MASTER_KEY = "sk-master-must-never-reach-an-agent"
BOT_TOKEN = "1234567:telegram-bot-token-must-never-reach-an-agent"

PROMPT = (
    "You are the implementer persona.\n\n"
    "## Scope\n\nImplement US1 of specs/003-merge-queue.\n"
    "Non-ASCII survives the pipe: — ✅ ✂\n"
)

#: Long enough that no test races its own deadline, short enough that a hung
#: adapter fails the suite rather than holding it open.
GENEROUS_TIMEOUT_S = 60

#: The deadline tests' bound, and the gap between TERM and KILL. Both small so
#: the escalation is observable in about a second and a half.
DEADLINE_S = 1
TEST_GRACE_S = 0.4

#: Ceiling for "the adapter is not wedged" assertions.
PATIENCE_S = 20.0


# --- setup -------------------------------------------------------------------


@pytest.fixture(autouse=True)
def fake_home(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """`HOME` for the *worker* side of the test: a recognizable operator path.

    Autouse because a test that forgot it would read the operator's real home —
    scripting the stub through whatever `~/stub-agent-control.json` happened to
    be lying around, and archiving from a real Claude Code history. The stub's
    control file is written into the *factory's* per-node home (the attempt
    context's `home_path`) so the child reads it from the home it is launched
    with, not from the worker's home.
    """
    home = tmp_path / "home"
    home.mkdir()
    monkeypatch.setenv("HOME", str(home))
    return home


@pytest.fixture(autouse=True)
def worker_env(monkeypatch: pytest.MonkeyPatch) -> None:
    """A worker host's environment: credentials, locale, and ordinary clutter.

    The credentials are planted for every test in this file, not just the one
    that names them — the allowlist's promise is that no launch anywhere can
    carry them, and a fixture that only appeared in the leak test would leave
    every other path unwatched.
    """
    monkeypatch.setenv("LITELLM_MASTER_KEY", MASTER_KEY)
    monkeypatch.setenv("TELEGRAM_BOT_TOKEN", BOT_TOKEN)
    monkeypatch.setenv("LITELLM_PROXY_URL", "http://litellm.test:4000")
    monkeypatch.setenv("LANG", "en_US.UTF-8")
    monkeypatch.setenv("TERM", "dumb")
    # Not a credential and still not the agent's business: the allowlist is
    # closed, so an ordinary variable is dropped exactly like a secret.
    monkeypatch.setenv("EDITOR", "vim")


@pytest.fixture
def worktree(tmp_path: Path) -> Path:
    """Where the agent runs. A directory, not a repository — see the docstring."""
    path = tmp_path / "worktrees" / EPIC / NODE
    path.mkdir(parents=True)
    return path


@pytest.fixture
def factory_root(tmp_path: Path) -> Path:
    """The worker host's state directory: transcripts, pid files (plan.md)."""
    return tmp_path / ".factory"


@pytest.fixture
def stub_home_dir(factory_root: Path) -> Path:
    """The factory's per-node home: where the stub reads its control file."""
    return home_path(factory_root, EPIC, NODE)


@pytest.fixture
def attempt(worktree: Path, stub_home_dir: Path) -> Callable[..., AttemptContext]:
    """Build the attempt's context; `attempt(timeout_s=1)` overrides one field."""

    def build(**overrides: Any) -> AttemptContext:
        fields: dict[str, Any] = {
            "epic_id": EPIC,
            "node_id": NODE,
            "attempt": ATTEMPT,
            "prompt": PROMPT,
            "worktree_path": str(worktree),
            "home_path": str(stub_home_dir),
            "proxy_url": PROXY_URL,
            "virtual_key": VIRTUAL_KEY,
            "model_alias": MODEL_ALIAS,
            "session_id": SESSION_ID,
            "timeout_s": GENEROUS_TIMEOUT_S,
        }
        return AttemptContext(**(fields | overrides))

    return build


@pytest.fixture
def adapter(stub_home_dir: Path) -> ClaudeCodeAdapter:
    """The real adapter, pointed at the stub instead of `claude`.

    The stub's control file is written into the factory's per-node home so the
    child reads it from the `HOME` the adapter constructs.
    """
    adapter = ClaudeCodeAdapter(
        executable=str(STUB_AGENT_PATH),
        grace_s=TEST_GRACE_S,
        backend=HostAgentBackend(executable=str(STUB_AGENT_PATH)),
    )
    adapter._node_home_for_control = stub_home_dir  # type: ignore[attr-defined]
    return adapter


@pytest.fixture
def spawn_orphan() -> Iterator[Callable[[], subprocess.Popen[bytes]]]:
    """Start a process in its own session — an agent the worker host forgot (R4).

    Its own session makes its pid its process-group id, which is what a pid file
    from a crashed worker names. Anything still alive at teardown is killed, so a
    failing assertion cannot leave a sleeper behind.
    """
    spawned: list[subprocess.Popen[bytes]] = []

    def spawn() -> subprocess.Popen[bytes]:
        process = subprocess.Popen(
            [sys.executable, "-c", "import time; time.sleep(300)"],
            stdin=subprocess.DEVNULL,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            start_new_session=True,
        )
        spawned.append(process)
        return process

    yield spawn

    for process in spawned:
        if process.poll() is None:
            process.kill()
        with contextlib.suppress(subprocess.TimeoutExpired):
            process.wait(timeout=PATIENCE_S)


# --- helpers -----------------------------------------------------------------


async def wait_until(
    predicate: Callable[[], bool], *, what: str, timeout_s: float = PATIENCE_S
) -> None:
    """Poll `predicate` until it holds, or fail naming what never happened."""
    deadline = time.monotonic() + timeout_s
    while time.monotonic() < deadline:
        if predicate():
            return
        await asyncio.sleep(0.02)
    raise AssertionError(f"timed out after {timeout_s}s waiting for {what}")


def stub_is_up(worktree: Path) -> bool:
    """Whether a launched stub has finished recording itself.

    Keyed on the stdin record because the stub writes it last, once the prompt is
    drained: by then argv, env, cwd and the process ids are all on disk.
    """
    return bool(list(worktree.glob(".stub-agent/*/stdin.txt")))


def plant_pid_file(factory_root: Path, contents: str) -> Path:
    """Leave `.factory/run/<epic>/<node>.pid` behind, as a dead worker would."""
    path = pid_file(factory_root, EPIC, NODE)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(contents, encoding="utf-8")
    return path


def pid_alive(pid: int) -> bool:
    """Whether signal 0 still finds `pid` (a zombie counts as alive — it exists)."""
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        return True
    return True


def archive_dir(factory_root: Path, attempt_number: int = ATTEMPT) -> Path:
    return transcript_dir(factory_root, EPIC, NODE, attempt_number)


def stdout_log(factory_root: Path, attempt_number: int = ATTEMPT) -> str:
    return (archive_dir(factory_root, attempt_number) / STDOUT_LOG_NAME).read_text(
        encoding="utf-8"
    )


def archived_transcript_events(factory_root: Path, attempt_number: int = ATTEMPT) -> list[str]:
    """The `event` field of each record in the archived session transcript.

    `["start"]` alone is a run that was killed between the two writes — the
    partial evidence FR-007 exists to keep.
    """
    path = archive_dir(factory_root, attempt_number) / f"{SESSION_ID}.jsonl"
    lines = path.read_text(encoding="utf-8").splitlines()
    return [json.loads(line)["event"] for line in lines if line.strip()]


def git_commit_in_child_environment(
    cwd: Path,
    home: Path,
    env: dict[str, str],
) -> subprocess.CompletedProcess[str]:
    """Make a git commit inside `cwd` using only the constructed child environment.

    The environment is the adapter's `attempt_env` output plus `ATTEMPT_ARCHIVE`
    if present. This is *not* a test helper that smuggles `GIT_AUTHOR_*` in:
    the assertion is that the home's `.gitconfig` provides identity.
    """
    return subprocess.run(
        ["git", "commit", "--quiet", "--allow-empty", "-m", "agent commit"],
        cwd=str(cwd),
        env=env,
        capture_output=True,
        text=True,
    )


def git_show_field(cwd: Path, field: str) -> str:
    """One commit field, e.g. `%an` or `%ae`, from HEAD."""
    return subprocess.run(
        ["git", "-C", str(cwd), "log", "-1", f"--format={field}"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()


# --- home path helper (US1) ----------------------------------------------------


def test_home_path_is_keyed_per_node_under_factory_root() -> None:
    """The home is a factory-owned directory, keyed like the worktree and pid file.

    Per-node, not per-attempt: retries share the tree they are retrying in and
    share the state beside it (FR-003).
    """
    root = Path("/tmp/factory-root")
    assert home_path(root, EPIC, NODE) == root / "homes" / EPIC / NODE


def test_home_paths_for_two_nodes_differ() -> None:
    """Two concurrently dispatched nodes must never write one configuration file."""
    root = Path("/tmp/factory-root")
    assert home_path(root, EPIC, "us1") != home_path(root, EPIC, "us2")


def test_home_path_is_the_same_across_attempts_of_one_node() -> None:
    """A node's retries reuse its one home the same way they reuse its worktree."""
    root = Path("/tmp/factory-root")
    assert home_path(root, EPIC, NODE) == home_path(root, EPIC, NODE)


# --- the seam (D-018) ---------------------------------------------------------


def test_the_registrys_agent_field_names_the_adapter() -> None:
    """A persona says `agent: claude-code`; that string resolves to the class."""
    resolved = adapter_for("claude-code")

    assert isinstance(resolved, ClaudeCodeAdapter)
    assert resolved.name == "claude-code"


# --- the conformance suite (154-US4-S3) ------------------------------------------
#
# The lesson of `ci/the-adapter-conformance-suite-is-a-hardcoded-list-of-one`:
# a suite that enumerates its own subjects cannot notice a new subject breaking
# the seam. These read `_ADAPTERS` at collection time, so the second adapter is
# swept the moment it is registered — and a conformance assertion that fails for
# `claude-code` fails for every adapter, not just the one the suite was written
# against.


def registered_agents() -> list[str]:
    """Every shipped agent, read off the registry rather than written down."""
    return sorted(_ADAPTERS)


CONFORMANCE_AGENTS = registered_agents()


@pytest.mark.parametrize("agent_name", CONFORMANCE_AGENTS)
def test_every_registered_adapter_resolves_by_its_own_name(agent_name: str) -> None:
    """The name the persona registry writes is the name that resolves."""
    resolved = adapter_for(agent_name)

    assert resolved.name == agent_name


@pytest.mark.parametrize("agent_name", CONFORMANCE_AGENTS)
def test_every_registered_adapter_keeps_the_one_method_protocol(agent_name: str) -> None:
    """US4-S2, swept: no adapter resurrects the five-method protocol — the outer
    surface is `run_attempt` and nothing else, whatever the inner seam does."""
    resolved = adapter_for(agent_name)

    methods = {
        name
        for name, value in vars(type(resolved)).items()
        if not name.startswith("_") and callable(value)
    }
    assert methods == {"run_attempt"}, (
        f"{type(resolved).__name__} exposes {sorted(methods)}; the outer protocol "
        "is one method (D-018, US4-S2) — the per-CLI seam is private"
    )


# --- launch: environment (US2-S1) ---------------------------------------------


async def test_the_child_environment_is_exactly_the_allowlist(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
) -> None:
    """Seven variables, no more: the table in contracts/adapter.md § Environment.

    The six the worker supplies (the two attempt credentials plus the three
    remaining passthroughs and the constructed `HOME`) plus `ATTEMPT_ARCHIVE` —
    the attempt's archive directory, which the adapter constructs rather than
    passthroughs, the way it constructs the two attempt credentials (008-US3).
    US1 makes `HOME` a constructed value too: it names the factory's per-node
    home, not the worker's.
    """
    expected_home = _expected_node_home(factory_root)
    write_control(stub_home_dir)

    await adapter.run_attempt(attempt(), factory_root=factory_root)

    env = last_invocation(worktree).env
    assert set(env) == {
        "ANTHROPIC_BASE_URL",
        "ANTHROPIC_AUTH_TOKEN",
        "PATH",
        "HOME",
        "LANG",
        "TERM",
        "ATTEMPT_ARCHIVE",
    }
    assert env["ANTHROPIC_BASE_URL"] == PROXY_URL
    assert env["ANTHROPIC_AUTH_TOKEN"] == VIRTUAL_KEY
    assert env["PATH"] == os.environ["PATH"]
    assert env["HOME"] == str(expected_home)
    assert env["LANG"] == "en_US.UTF-8"
    assert env["TERM"] == "dumb"
    # 008-US3: the archive directory the agent writes its ferry question to.
    assert env["ATTEMPT_ARCHIVE"] == str(archive_dir(factory_root))


async def test_no_worker_credential_reaches_the_agent(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
) -> None:
    """US2-S1: never the master key or the bot token — by omission, not redaction.

    The values are checked as well as the names: a "scrubbed" environment that
    smuggled the master key through under `ANTHROPIC_AUTH_TOKEN` would satisfy a
    name-only assertion and hand an agent the keys to the proxy.
    """
    write_control(stub_home_dir)

    await adapter.run_attempt(attempt(), factory_root=factory_root)

    env = last_invocation(worktree).env
    assert "LITELLM_MASTER_KEY" not in env
    assert "TELEGRAM_BOT_TOKEN" not in env
    assert "LITELLM_PROXY_URL" not in env
    assert "EDITOR" not in env
    assert MASTER_KEY not in env.values()
    assert BOT_TOKEN not in env.values()


async def test_a_declared_context_window_suppresses_the_unrecognized_model_warning(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
) -> None:
    """US4-S5: when the persona declares a window, the CLI stops assuming 200,000.

    The factory cannot discover the real window (the proxy reports null for every
    custom alias), so the declaration is the only signal the CLI receives. The
    stub stands in for the CLI: it emits the warning when no window is declared
    and omits it when one is, so the archived stdout proves the env var did its
    job.
    """
    write_control(stub_home_dir)

    await adapter.run_attempt(attempt(context_window=128000), factory_root=factory_root)

    log = stdout_log(factory_root)
    assert BANNER in log
    assert "200,000" not in log
    assert UNRECOGNIZED_MODEL_WARNING not in log
    assert last_invocation(worktree).env["CLAUDE_CODE_MAX_CONTEXT_TOKENS"] == "128000"


def test_attempt_env_omits_a_passthrough_the_worker_does_not_set(
    attempt: Callable[..., AttemptContext],
    factory_root: Path,
) -> None:
    """The pure builder: passthrough is passthrough, not invention.

    A worker without `LANG` gives a child without `LANG` — an empty string here
    would be the factory asserting a locale nobody configured. `HOME` is a
    constructed value from the context, so the worker's `HOME` does not reach
    the child even when set.
    """
    env = attempt_env(
        attempt(),
        {"PATH": "/usr/bin:/bin", "HOME": "/home/worker", "LITELLM_MASTER_KEY": MASTER_KEY},
    )

    assert env == {
        "ANTHROPIC_BASE_URL": PROXY_URL,
        "ANTHROPIC_AUTH_TOKEN": VIRTUAL_KEY,
        "PATH": "/usr/bin:/bin",
        "HOME": str(_expected_node_home(factory_root)),
    }


# --- launch: the invocation (US2-S1, R6) --------------------------------------


async def test_the_prompt_arrives_on_stdin_verbatim(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
) -> None:
    """stdin, not argv: assembled prompts run to hundreds of KB (ARG_MAX, R6).

    That the stub returns at all is half the assertion — an adapter that wrote
    the prompt without closing the pipe would leave it blocked in `read()` until
    the deadline.
    """
    write_control(stub_home_dir)

    await adapter.run_attempt(attempt(), factory_root=factory_root)

    assert last_invocation(worktree).stdin == PROMPT


def _expected_node_home(factory_root: Path, epic: str = EPIC, node: str = NODE) -> Path:
    return home_path(factory_root, epic, node)


def test_attempt_env_replaces_home_with_the_factory_per_node_path(
    attempt: Callable[..., AttemptContext],
    factory_root: Path,
) -> None:
    """US1: the child's `HOME` is built, not passed through (FR-001, FR-002).

    The worker's `HOME` is a recognizable operator path and also carries
    credentials; the built environment must contain none of that surface and must
    still include `HOME` so `_archive_session` can resolve the transcript.
    """
    operator_home = "/home/operator"
    env = attempt_env(
        attempt(),
        {
            "PATH": "/usr/bin",
            "HOME": operator_home,
            "LANG": "en_US.UTF-8",
            "TERM": "dumb",
            "LITELLM_MASTER_KEY": MASTER_KEY,
            "TELEGRAM_BOT_TOKEN": BOT_TOKEN,
            "SOME_FUTURE_CREDENTIAL": "sk-not-invented-yet",
        },
    )
    assert env == {
        "ANTHROPIC_BASE_URL": PROXY_URL,
        "ANTHROPIC_AUTH_TOKEN": VIRTUAL_KEY,
        "PATH": "/usr/bin",
        "HOME": str(_expected_node_home(factory_root)),
        "LANG": "en_US.UTF-8",
        "TERM": "dumb",
    }
    assert not any(value.startswith(operator_home) for value in env.values())


def test_attempt_env_keeps_home_present_even_without_worker_home(
    attempt: Callable[..., AttemptContext],
    factory_root: Path,
) -> None:
    """FR-002: omitting the name would silently disable transcript archiving.

    `_archive_session` returns early on a missing `HOME`, so the builder must
    write it from the context even when the worker environment carries none.
    """
    env = attempt_env(
        attempt(),
        {"PATH": "/usr/bin"},
    )
    assert "HOME" in env
    assert env["HOME"] == str(_expected_node_home(factory_root))


async def test_the_factory_home_is_created_before_the_agent_launches(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
) -> None:
    """FR-003: the directory must exist before the child starts.

    The stub records the home it saw; the assertion is on the filesystem so a
    race where creation happens *after* spawn fails the test.
    """
    expected = _expected_node_home(factory_root)
    assert not expected.exists(), "the test precondition is a not-yet-created home"
    write_control(stub_home_dir)

    await adapter.run_attempt(attempt(), factory_root=factory_root)

    assert expected.is_dir()
    assert last_invocation(worktree).env["HOME"] == str(expected)


async def test_a_home_that_cannot_be_created_raises_adapter_error(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
) -> None:
    """FR-003: an infrastructure failure, never a fallback to the worker's home.

    Making the parent a file removes the ability to create the home directory,
    which must raise `AdapterError` naming the path.
    """
    # Make the parent path a file, so `mkdir(parents=True)` cannot succeed.
    factory_root.mkdir(parents=True, exist_ok=True)
    block = factory_root / "homes"
    block.write_text("not a directory", encoding="utf-8")

    # `write_control` wants to create stub_home_dir, which is now blocked by the
    # file we just wrote. Write the control file one level above (where creation
    # still works) so the failure under test is the *adapter's* home creation,
    # not the test setup's.
    control_home = factory_root / "control-home"
    control_home.mkdir(parents=True, exist_ok=True)
    write_control(control_home)

    with pytest.raises(AdapterError) as raised:
        await adapter.run_attempt(attempt(), factory_root=factory_root)

    assert str(_expected_node_home(factory_root)) in str(raised.value)
    assert not any(value == str(fake_home) for value in raised.value.__dict__.values())


async def test_the_agent_runs_in_the_nodes_worktree(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
) -> None:
    """FR-013's isolation is a cwd: the agent sees its node's tree and nothing else."""
    write_control(stub_home_dir)

    await adapter.run_attempt(attempt(), factory_root=factory_root)

    assert Path(last_invocation(worktree).cwd) == worktree.resolve()


async def test_argv_carries_the_model_alias_and_the_generated_session_id(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
) -> None:
    """`claude -p --dangerously-skip-permissions --model <alias> --session-id <uuid>`.

    The alias travels from the persona registry through argv — the adapter names
    no model (constitution VII) — and the session id is what makes the transcript
    discoverable afterwards (R6).
    """
    write_control(stub_home_dir)

    await adapter.run_attempt(attempt(), factory_root=factory_root)

    argv = last_invocation(worktree).argv
    assert "-p" in argv
    assert "--dangerously-skip-permissions" in argv
    assert last_invocation(worktree).flag("--model") == MODEL_ALIAS
    assert last_invocation(worktree).flag("--session-id") == SESSION_ID


async def test_the_default_executable_is_claude_found_on_the_childs_path(
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Nothing configures the binary: `claude` is resolved from the passed-through
    `PATH`, which is the only reason passing `PATH` through matters at all."""
    bin_dir = tmp_path / "bin"
    install_as(bin_dir, "claude")
    monkeypatch.setenv("PATH", f"{bin_dir}{os.pathsep}{os.environ['PATH']}")
    write_control(stub_home_dir)

    result = await ClaudeCodeAdapter(
        grace_s=TEST_GRACE_S,
        backend=HostAgentBackend(),
    ).run_attempt(attempt(), factory_root=factory_root)

    assert result.termination == Termination.COMPLETED
    assert Path(last_invocation(worktree).argv[0]).name == "claude"


# --- classification (US2-S2) ---------------------------------------------------


async def test_a_clean_exit_is_completed(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
) -> None:
    """Exit 0 is the whole of the signal — COMPLETED is a process fact, not a
    claim of success (FR-012). The verdict comes from 002, later."""
    write_control(stub_home_dir, exit_code=0, stdout="I have completed the task.")

    result = await adapter.run_attempt(attempt(), factory_root=factory_root)

    assert isinstance(result, AdapterResult)
    assert result.termination == Termination.COMPLETED


async def test_a_non_zero_exit_is_an_agent_error(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
) -> None:
    """Any non-zero code, unexamined: the exit status is not a diagnosis."""
    write_control(stub_home_dir, exit_code=3, stderr="context window exceeded")

    result = await adapter.run_attempt(attempt(), factory_root=factory_root)

    assert result.termination == Termination.AGENT_ERROR


async def test_agent_output_never_reaches_the_result(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
) -> None:
    """FR-012: an agent that declares failure while exiting 0 still terminates
    COMPLETED, and the log holds the words the result does not."""
    write_control(
        stub_home_dir, exit_code=0, stdout="FAILED: I could not do it", stderr="ERROR ERROR"
    )

    result = await adapter.run_attempt(attempt(), factory_root=factory_root)

    assert result.termination == Termination.COMPLETED
    log = stdout_log(factory_root)
    assert "FAILED: I could not do it" in log
    # stderr is merged into the one log: interleaved as the agent wrote it.
    assert "ERROR ERROR" in log


# --- the deadline (US2-S3) -----------------------------------------------------


async def test_a_run_that_outlives_its_deadline_is_terminated_and_classified_timeout(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
) -> None:
    """TERM to the group, grace, then KILL — enforced in-activity, not by Temporal.

    The stub ignores SIGTERM and spawns a child of its own, so both halves are
    observable: its signal log records the TERM it survived, and the grandchild —
    reachable only through the process *group* — is gone by the end. A run that
    ignored TERM and still ended can only have ended on KILL.
    """
    write_control(
        stub_home_dir, sleep_s=300.0, ignore_sigterm=True, spawn_child=True, child_sleep_s=300.0
    )
    started = time.monotonic()

    result = await adapter.run_attempt(
        attempt(timeout_s=DEADLINE_S), factory_root=factory_root
    )
    elapsed = time.monotonic() - started

    assert result.termination == Termination.TIMEOUT
    assert elapsed < PATIENCE_S, "the deadline was not enforced in-activity"

    invocation = last_invocation(worktree)
    assert any(entry.startswith("TERM") for entry in invocation.signals)

    grandchild = invocation.child_pid
    assert grandchild is not None
    await wait_until(
        lambda: not pid_alive(grandchild), what="the agent's child to be killed too"
    )


async def test_a_deadline_leaves_the_evidence_the_run_produced(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
) -> None:
    """FR-007 on the killed path: a partial transcript is the only account there is.

    The stub writes its `start` record before sleeping and its `end` record after,
    so an archive holding `start` alone is proof that what existed at the moment
    of death was kept — not that a tidy run was copied afterwards.
    """
    write_control(stub_home_dir, sleep_s=300.0, stdout="working on it")

    result = await adapter.run_attempt(
        attempt(timeout_s=DEADLINE_S), factory_root=factory_root
    )

    assert result.termination == Termination.TIMEOUT
    assert Path(result.transcript_path) == archive_dir(factory_root)
    assert "working on it" in stdout_log(factory_root)
    assert archived_transcript_events(factory_root) == [TRANSCRIPT_START]


# --- the archive (US2-S4, FR-007) ----------------------------------------------


async def test_the_attempt_directory_holds_the_log_and_the_session_transcript(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
    worktree: Path,
) -> None:
    """`.factory/transcripts/<epic>/<node>/attempt-<n>/`, keyed by attribution."""
    write_control(stub_home_dir)

    result = await adapter.run_attempt(attempt(), factory_root=factory_root)

    expected = factory_root / "transcripts" / EPIC / NODE / f"attempt-{ATTEMPT}"
    assert Path(result.transcript_path) == expected
    assert expected.is_dir()

    assert BANNER in (expected / STDOUT_LOG_NAME).read_text(encoding="utf-8")

    # A copy, not a move: the session file the agent wrote is still where it was,
    # and the archived bytes are the same bytes.
    source = session_transcript_path(stub_home_dir, worktree, SESSION_ID)
    assert source.is_file()
    assert (expected / f"{SESSION_ID}.jsonl").read_bytes() == source.read_bytes()
    assert archived_transcript_events(factory_root) == [TRANSCRIPT_START, TRANSCRIPT_END]


async def test_an_agent_that_wrote_no_transcript_still_archives_its_output(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
) -> None:
    """A missing session file is not a missing archive: the log is still evidence,
    and a crash on the archive step would cost the attempt its whole record."""
    write_control(stub_home_dir, write_transcript=False, exit_code=1)

    result = await adapter.run_attempt(attempt(), factory_root=factory_root)

    # The archive is this test's subject and is unchanged. The classification
    # beside it moved with 095-US1: a non-zero exit with no session transcript
    # behind it is the pre-agent class now, because no turn ran — which is the
    # very shape this fixture scripts.
    assert result.termination == Termination.PRE_AGENT_FAILURE
    assert Path(result.transcript_path) == archive_dir(factory_root)
    assert BANNER in stdout_log(factory_root)
    assert not (archive_dir(factory_root) / f"{SESSION_ID}.jsonl").exists()


async def test_each_attempt_archives_under_its_own_number(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
) -> None:
    """Retries share the worktree (FR-013) and must not share the record: the
    prior attempt's evidence is what a retry prompt quotes (FR-006)."""
    write_control(stub_home_dir, stdout="first")
    first = await adapter.run_attempt(attempt(attempt=1), factory_root=factory_root)

    write_control(stub_home_dir, stdout="second")
    second = await adapter.run_attempt(attempt(attempt=2), factory_root=factory_root)

    assert first.transcript_path != second.transcript_path
    assert "first" in stdout_log(factory_root, 1)
    assert "second" in stdout_log(factory_root, 2)
    assert "second" not in stdout_log(factory_root, 1)


async def test_transcripts_never_land_inside_the_worktree(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
    worktree: Path,
) -> None:
    """FR-007: they stay on the worker host. Inside the tree, salvage would commit
    the agent's own transcript to the node branch and the diff check would read it
    as work."""
    write_control(stub_home_dir)

    result = await adapter.run_attempt(attempt(), factory_root=factory_root)

    archive = Path(result.transcript_path).resolve()
    assert not archive.is_relative_to(worktree.resolve())
    assert not list(worktree.rglob(STDOUT_LOG_NAME))
    assert not list(worktree.rglob("*.jsonl"))


# --- reaping an orphan (R4) ----------------------------------------------------


async def test_a_live_process_group_from_a_previous_run_is_reaped_before_relaunch(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
    spawn_orphan: Callable[[], subprocess.Popen[bytes]],
) -> None:
    """The worker died mid-attempt; Temporal retried; the old agent is still there.

    Two agents in one worktree is corruption, so the check is *before* the launch
    — asserted by looking at the orphan the moment the new stub reports itself up,
    not merely at the end of the run.
    """
    orphan = spawn_orphan()
    plant_pid_file(factory_root, f"{orphan.pid}\n")
    write_control(stub_home_dir, sleep_s=2.0)

    run = asyncio.create_task(adapter.run_attempt(attempt(), factory_root=factory_root))
    try:
        await wait_until(lambda: stub_is_up(worktree), what="the new agent to launch")
        assert orphan.poll() is not None, "the orphan was still alive at relaunch"
    finally:
        result = await run

    assert result.termination == Termination.COMPLETED
    assert orphan.wait(timeout=PATIENCE_S) in (-signal.SIGTERM, -signal.SIGKILL)


async def test_the_pid_file_names_this_attempts_group_and_is_removed_on_exit(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
) -> None:
    """The file is the next run's only handle on this one (R4), so it names the
    process *group* — the agent's children are what have to die with it — and it
    goes away on a clean exit, because a stale pid is a reap of somebody else."""
    write_control(stub_home_dir, sleep_s=2.0)
    path = pid_file(factory_root, EPIC, NODE)

    run = asyncio.create_task(adapter.run_attempt(attempt(), factory_root=factory_root))
    try:
        await wait_until(lambda: stub_is_up(worktree), what="the agent to launch")
        assert path.is_file()
        assert int(path.read_text(encoding="utf-8").strip()) == last_invocation(worktree).pgid
    finally:
        await run

    assert not path.exists()


@pytest.mark.parametrize(
    "planted",
    [
        pytest.param("", id="empty"),
        pytest.param("not-a-pid\n", id="garbage"),
        # A worker killed mid-write can leave anything here, and `killpg(0, …)`
        # means "this process group" — the worker's own. It must never be sent.
        pytest.param("0\n", id="zero"),
    ],
)
async def test_an_unusable_pid_file_is_not_an_error(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
    planted: str,
) -> None:
    """Reaping is a precaution, not a gate: garbage from a crashed worker must not
    cost the node its attempt."""
    plant_pid_file(factory_root, planted)
    write_control(stub_home_dir)

    result = await adapter.run_attempt(attempt(), factory_root=factory_root)

    assert result.termination == Termination.COMPLETED


async def test_a_pid_file_naming_a_dead_process_is_not_an_error(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
    spawn_orphan: Callable[[], subprocess.Popen[bytes]],
) -> None:
    """The ordinary case: the previous attempt exited but never got to tidy up."""
    departed = spawn_orphan()
    departed.kill()
    departed.wait(timeout=PATIENCE_S)
    plant_pid_file(factory_root, f"{departed.pid}\n")
    write_control(stub_home_dir)

    result = await adapter.run_attempt(attempt(), factory_root=factory_root)

    assert result.termination == Termination.COMPLETED


async def test_with_no_recorded_predecessor_nothing_is_reaped(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
    spawn_orphan: Callable[[], subprocess.Popen[bytes]],
) -> None:
    """The control for 082 US5-S4: the reap is keyed on the record, not a scan.

    A capped heartbeat timeout (082 FR-008) makes the false positive routine —
    the server misses beats while the agent lives — so the retry's reap now runs
    far more often, and every extra firing is a chance to kill the wrong thing.
    The record is the only thing that identifies a predecessor: with none, the
    live processes on the worker host are nobody's predecessor and must be left
    exactly as they are.
    """
    bystander = spawn_orphan()
    assert not pid_file(factory_root, EPIC, NODE).exists()
    write_control(stub_home_dir)

    result = await adapter.run_attempt(attempt(), factory_root=factory_root)

    assert result.termination == Termination.COMPLETED
    assert bystander.poll() is None, "a process no pid file recorded was signalled"


async def test_the_pid_record_never_lands_inside_the_worktree(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
    worktree: Path,
) -> None:
    """FR-009: the record is sidecar evidence on the worker host, like the
    transcripts above and for the same reason.

    Inside the tree it would be committed by salvage and then read by
    `read_worktree_diff`, the gates and the judge as the attempt's own work.
    Checked while the agent is live, because that is the only moment the file
    exists — a clean exit clears it.
    """
    write_control(stub_home_dir, sleep_s=2.0)
    path = pid_file(factory_root, EPIC, NODE)
    assert not path.resolve().is_relative_to(worktree.resolve())

    run = asyncio.create_task(adapter.run_attempt(attempt(), factory_root=factory_root))
    try:
        await wait_until(path.is_file, what="the pid record to be written")
        assert not list(worktree.rglob("*.pid"))
    finally:
        result = await run

    assert result.termination == Termination.COMPLETED


# --- monitoring (R2) -----------------------------------------------------------


async def test_the_adapter_beats_while_it_waits(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
) -> None:
    """The heartbeat is a callback, not an import of Temporal: the activity passes
    `activity.heartbeat`, which is what makes an hours-long attempt cancellable
    and a dead worker detectable in minutes rather than at the deadline (R2)."""
    beats: list[int] = []
    write_control(stub_home_dir, sleep_s=1.0)

    result = await adapter.run_attempt(
        attempt(),
        factory_root=factory_root,
        heartbeat=lambda _snapshot: beats.append(1),
        heartbeat_interval_s=0.05,
    )

    assert result.termination == Termination.COMPLETED
    assert len(beats) >= 3, f"expected repeated beats over a 1s run, got {len(beats)}"


# --- US1: the heartbeat carries the usage snapshot ----------------------------
#
# Observation moves inside the adapter (plan US1): the monitor beats once per
# `heartbeat_interval_s` and reads the proxy once per `poll_interval_s`, carrying
# the newest snapshot (or `None` before any reading exists) as the heartbeat's
# details. The heartbeat signature gains the snapshot, and the usage read is a
# callable the adapter is handed — failure-isolated so a dead spend read can
# never kill liveness (the beat still fires).


def _usage_snapshot(spend: float = 1.25) -> UsageSnapshot:
    return UsageSnapshot(spend_usd=spend, captured_at="2026-08-05T09:31:00Z")


async def test_the_heartbeat_carries_none_then_a_snapshot(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
) -> None:
    """Before the first successful read the beat carries `None`; after it, the
    snapshot — so teardown's fallback can tell "never measured" from "measured".

    The first beat fires one `heartbeat_interval_s` in, before the first read
    (`poll_interval_s`) has completed, so it is necessarily `None`; every later
    beat carries the reading once one exists.
    """
    write_control(stub_home_dir, sleep_s=0.4)
    seen: list[UsageSnapshot | None] = []

    async def read_usage() -> UsageSnapshot:
        return _usage_snapshot()

    result = await adapter.run_attempt(
        attempt(),
        factory_root=factory_root,
        heartbeat=seen.append,
        heartbeat_interval_s=0.02,
        poll_interval_s=0.1,
        read_usage=read_usage,
    )

    assert result.termination == Termination.COMPLETED
    assert seen[0] is None, "the first beat predates any usage reading"
    assert any(isinstance(s, UsageSnapshot) for s in seen), (
        "no beat ever carried a snapshot once a reading existed"
    )


async def test_a_failing_usage_read_leaves_the_previous_snapshot_and_still_beats(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
) -> None:
    """A spend read that raises keeps the previous snapshot in place and never
    kills the beat: liveness and spend share one channel, and spend must not be
    able to kill liveness (plan US1).

    The first read succeeds; every subsequent one fails. Beats after the first
    failed read must still fire and must still carry the first snapshot — the
    number that was true a beat ago, not `None` (constitution V).
    """
    write_control(stub_home_dir, sleep_s=0.4)
    seen: list[UsageSnapshot | None] = []
    calls = {"n": 0}

    async def read_usage() -> UsageSnapshot:
        calls["n"] += 1
        if calls["n"] == 1:
            return _usage_snapshot()
        raise RuntimeError("proxy unreachable")

    result = await adapter.run_attempt(
        attempt(),
        factory_root=factory_root,
        heartbeat=seen.append,
        heartbeat_interval_s=0.02,
        poll_interval_s=0.05,
        read_usage=read_usage,
    )

    assert result.termination == Termination.COMPLETED
    assert calls["n"] > 1, "expected more than one usage read over the run"
    assert len(seen) >= 3, f"a failing read killed the beat; got {len(seen)} beats"
    assert seen[-1] == _usage_snapshot(), (
        "a failing read discarded the previous snapshot and beat carried None"
    )


async def test_the_proxy_is_read_at_most_once_per_poll_interval(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
) -> None:
    """The proxy is read once per `poll_interval_s`, whatever the beat interval.

    The beat is what makes an attempt cancellable and may fire many times per
    proxy read; the read is a proxy round trip and is throttled to its own, much
    slower cadence (plan US1). A beat that outnumbers reads proves the read is
    bounded independently of the beat.
    """
    write_control(stub_home_dir, sleep_s=0.4)
    beats: list[UsageSnapshot | None] = []
    calls = {"n": 0}

    async def read_usage() -> UsageSnapshot:
        calls["n"] += 1
        return _usage_snapshot()

    result = await adapter.run_attempt(
        attempt(),
        factory_root=factory_root,
        heartbeat=beats.append,
        heartbeat_interval_s=0.01,
        poll_interval_s=0.1,
        read_usage=read_usage,
    )

    assert result.termination == Termination.COMPLETED
    # ~0.4s at one read per 0.1s is at most 4-5 reads, against ~40 beats.
    assert calls["n"] <= 5, f"proxy read not bounded by poll_interval: {calls['n']} reads"
    assert len(beats) > calls["n"], (
        "the proxy was read at least as often as the beat fired; "
        "the read cadence is not independent of the beat"
    )


# --- US1: the heartbeat payload round-trips the data converter -----------------
#
# The snapshot rides the activity's heartbeat, whose payload crosses Temporal's
# data converter both ways. A payload that fails to serialise degrades the beat
# to liveness-only *silently* (plan US1), so the round-trip is asserted directly
# rather than inferred — a beat that still fires but carries nothing would pass
# every liveness test and fail teardown's fallback.


async def test_the_heartbeat_payload_round_trips_the_default_data_converter() -> None:
    """`UsageSnapshot | None`, as carried on the heartbeat, survives Temporal's
    default converter unchanged — the value teardown falls back to when the
    proxy is unreadable must be the value that was measured, not a serialised
    ghost of it."""
    payloads = await DataConverter.default.encode([_usage_snapshot(), None])
    decoded = await DataConverter.default.decode(
        payloads, [UsageSnapshot, Optional[UsageSnapshot]]
    )

    assert decoded[0] == _usage_snapshot()
    assert decoded[1] is None


# --- US3: the in-attempt ferry (FR-009) ----------------------------------------
#
# An agent that asks mid-flight keeps its process and its context alive while
# the answer travels. The channel is the filesystem the agent already owns
# (its archive directory, never the worktree) and the beat that already runs:
# the agent writes a `question` file and polls for an `answer` file; the
# adapter's monitor loop ferries the question up (a callable the activity wires
# to `send_question`) and the answer down (a callable that polls the store the
# bridge writes to). The ferry is bounded: a question with no answer in the
# window degrades to the US1 final-message path — the agent writes the
# OPERATOR QUESTION marker and exits — so the ferry can only improve the round
# trip, never hang it (FR-009).
#
# The same isolation 006-US1 requires of the usage read applies to the ferry
# read: a dead ferry call must never kill the liveness beat. The beat still
# fires while the question is in flight, and a `send_ferry_question` or
# `read_ferry_answer` that raises leaves the beat and the deadline intact.

#: A question body the stub writes to its ferry file. Distinctive so a leak into
#: the wrong surface is greppable, and long enough to be a real question.
FERRY_QUESTION = (
    "Should the ledger row key on (epic, node, attempt) or (epic, node, "
    "attempt, persona)? The plan says the former; the debugger re-entry (US2) "
    "re-issues under the same persona, which collides. My lean: add persona."
)

#: An answer the test's ferry callable returns, as the operator (via the
#: bridge) would. Distinctive from the question so "the answer reached the
#: agent" is observable in the stub's output.
FERRY_ANSWER = "Key on (epic, node, attempt, persona) — the collision is real."


async def _wait_for_question(factory_root: Path, timeout_s: float = PATIENCE_S) -> Path:
    """Block until the attempt's `question` ferry file appears in the archive.

    The stub writes it the moment its ferry logic runs, so this is the
    rendezvous: by the time it returns, the monitor loop's question read is
    about to fire (or already has).
    """
    archive = archive_dir(factory_root)
    deadline = time.monotonic() + timeout_s
    while time.monotonic() < deadline:
        path = archive / FERRY_QUESTION_FILE
        if path.is_file():
            return path
        await asyncio.sleep(0.01)
    raise AssertionError("the stub never wrote its ferry question file")


def _write_answer(factory_root: Path, answer: str) -> None:
    """Drop the answer file the polling agent is waiting for, as the monitor loop would."""
    archive = archive_dir(factory_root)
    (archive / FERRY_ANSWER_FILE).write_text(answer, encoding="utf-8")


async def test_the_attempt_archive_path_is_handed_to_the_agent(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
    worktree: Path,
) -> None:
    """The agent learns its archive directory from the environment the adapter
    builds, not from a worker path in the prompt (the prompt carries none).

    `$ATTEMPT_ARCHIVE` is the one place the agent can write a ferry file that
    salvage will never commit — it lives under `.factory/`, never in the
    worktree, the same discipline `stdout.log` already lives by (FR-007).
    """
    write_control(stub_home_dir)

    await adapter.run_attempt(attempt(), factory_root=factory_root)

    env = last_invocation(worktree).env
    assert ATTEMPT_ARCHIVE_ENV in env, (
        "the adapter did not hand the agent its archive directory"
    )
    assert env[ATTEMPT_ARCHIVE_ENV] == str(archive_dir(factory_root))


async def test_a_ferry_question_ships_upward_once(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
) -> None:
    """The monitor loop reads the question file and ships it up exactly once.

    A callable the activity wires to `send_question` receives the question text
    verbatim; the questions row + Telegram send are its concern, not the
    adapter's. Shipped once: the monitor loop does not re-send a question it
    already ferried, the way a heartbeat does not re-fire a beat it already
    fired.
    """
    write_control(stub_home_dir, ferry_question=FERRY_QUESTION, ferry_window_s=3.0)
    shipped: list[str] = []

    async def send_ferry_question(text: str) -> str:
        shipped.append(text)
        return "q-ferried"

    run = asyncio.create_task(
        adapter.run_attempt(
            attempt(),
            factory_root=factory_root,
            send_ferry_question=send_ferry_question,
        )
    )
    await _wait_for_question(factory_root)
    # Give the monitor loop a beat to read the file and ship it up.
    await wait_until(lambda: len(shipped) >= 1, what="the question to ship up")
    _write_answer(factory_root, FERRY_ANSWER)
    result = await run

    assert shipped == [FERRY_QUESTION], (
        f"the question shipped {len(shipped)} times, not once: {shipped}"
    )
    assert result.termination == Termination.COMPLETED


async def test_an_answer_is_delivered_to_the_polling_agent(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
) -> None:
    """The monitor loop ferries the answer down: it writes the answer file the
    polling agent reads, and the same process resumes and proceeds.

    The answer arrives via the activity's `read_ferry_answer` callable (the
    bridge wrote it to the store); the adapter writes it to the archive's
    `answer` file, and the in-flight agent reads it and commits work — no
    second dispatch, no cold re-read of the worktree (US3's whole point).
    """
    write_control(stub_home_dir, ferry_question=FERRY_QUESTION, ferry_window_s=5.0)

    async def send_ferry_question(text: str) -> str:
        return "q-ferried"

    answered = {"n": 0}

    async def read_ferry_answer(question_id: str) -> str | None:
        answered["n"] += 1
        # The first poll sees no answer; a later one sees it, the way the store
        # fills when the bridge routes the operator's reply.
        return FERRY_ANSWER if answered["n"] >= 2 else None

    run = asyncio.create_task(
        adapter.run_attempt(
            attempt(),
            factory_root=factory_root,
            send_ferry_question=send_ferry_question,
            read_ferry_answer=read_ferry_answer,
            ferry_interval_s=0.05,
        )
    )
    await _wait_for_question(factory_root)
    result = await run

    assert result.termination == Termination.COMPLETED
    # The agent read its answer and proceeded (no marker, no hang).
    log = stdout_log(factory_root)
    assert "## OPERATOR QUESTION" not in log, (
        "a ferry that got an answer degraded to the marker path anyway"
    )
    assert answered["n"] >= 2, "the adapter never polled for the answer"


async def test_an_unanswered_ferry_degrades_to_the_us1_marker_path(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
) -> None:
    """FR-009: an in-attempt ferry with no answer in the window degrades to the
    US1 final-message path — marker + QUESTION termination — never a hang or a
    timeout burn.

    The stub polls for an answer it is never given; when its window elapses it
    writes the OPERATOR QUESTION marker to stdout and exits 0. The adapter
    classifies COMPLETED (exit 0), and the marker in the archived log is what
    US1's detector would pick up — the ferry improved nothing and broke
    nothing, which is the whole guarantee.
    """
    write_control(stub_home_dir, ferry_question=FERRY_QUESTION, ferry_window_s=0.3)

    async def send_ferry_question(text: str) -> str:
        return "q-ferried"

    async def read_ferry_answer(question_id: str) -> str | None:
        # The operator never engages.
        return None

    started = time.monotonic()
    result = await adapter.run_attempt(
        attempt(timeout_s=GENEROUS_TIMEOUT_S),
        factory_root=factory_root,
        send_ferry_question=send_ferry_question,
        read_ferry_answer=read_ferry_answer,
    )
    elapsed = time.monotonic() - started

    assert result.termination == Termination.COMPLETED, (
        "an unanswered ferry burned the deadline rather than degrading"
    )
    # The agent proceeded to the US1 path: the marker is in the archived log,
    # which is what US1's detector scans (FR-009 — degrade to v0, never a hang).
    assert "## OPERATOR QUESTION" in stdout_log(factory_root)
    assert FERRY_QUESTION in stdout_log(factory_root)
    # The deadline was not burned: the stub gave up well before the generous
    # timeout. A ferry that hung would still be alive at GENEROUS_TIMEOUT_S.
    assert elapsed < 5.0, (
        f"the unanswered ferry did not degrade promptly ({elapsed:.1f}s)"
    )


async def test_the_ferry_read_never_blocks_or_kills_the_liveness_beat(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
) -> None:
    """The ferry read is isolated the way the usage read is (006-US1): a
    `send_ferry_question` or `read_ferry_answer` that raises leaves the previous
    state in place and the beat still fires — liveness and the ferry share one
    channel, and the ferry must not be able to kill liveness.

    Every ferry call raises; the agent still runs, still beats, and still
    degrades to the US1 path when its window elapses (FR-009). A ferry that
    could kill the beat would convert a question into a hang, which is exactly
    what the rule forbids.
    """
    write_control(stub_home_dir, ferry_question=FERRY_QUESTION, ferry_window_s=0.4)
    beats: list[UsageSnapshot | None] = []

    async def send_ferry_question(text: str) -> str:
        raise RuntimeError("notify unreachable")

    async def read_ferry_answer(question_id: str) -> str | None:
        raise RuntimeError("store unreadable")

    result = await adapter.run_attempt(
        attempt(),
        factory_root=factory_root,
        heartbeat=beats.append,
        heartbeat_interval_s=0.02,
        send_ferry_question=send_ferry_question,
        read_ferry_answer=read_ferry_answer,
    )

    assert result.termination == Termination.COMPLETED, (
        "a failing ferry read burned the deadline rather than degrading"
    )
    assert len(beats) >= 3, (
        f"a failing ferry read killed the beat; got {len(beats)} beats"
    )
    # The question shipped, but every answer read failed; the agent degraded to
    # the marker path the moment its window elapsed, the way FR-009 requires.
    assert "## OPERATOR QUESTION" in stdout_log(factory_root)


async def test_the_ferry_window_does_not_extend_the_attempts_deadline(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
) -> None:
    """Acceptance scenario 1: the same process resumes and the attempt's timeout
    clock is unaffected. The ferry polls on its own cadence inside the
    attempt's existing runtime — the deadline is the one the context declared,
    and a question in flight does not pause it.
    """
    write_control(stub_home_dir, ferry_question=FERRY_QUESTION, ferry_window_s=2.0)

    async def send_ferry_question(text: str) -> str:
        return "q-ferried"

    async def read_ferry_answer(question_id: str) -> str | None:
        return None

    # A deadline shorter than the ferry window: the attempt times out before the
    # agent gives up on its own, proving the clock was never paused for the
    # ferry (a paused clock would let the agent finish within the window).
    started = time.monotonic()
    result = await adapter.run_attempt(
        attempt(timeout_s=1),
        factory_root=factory_root,
        send_ferry_question=send_ferry_question,
        read_ferry_answer=read_ferry_answer,
    )
    elapsed = time.monotonic() - started

    assert result.termination == Termination.TIMEOUT, (
        "the ferry window paused the deadline; the clock must be unaffected"
    )
    assert elapsed < PATIENCE_S, "the deadline was not enforced against the ferry"


# --- US2: seeded home, git identity, and archive composition -----------------


async def test_a_seeded_home_contains_only_factory_authored_files(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
) -> None:
    """FR-004: the home is a factory-authored surface, not a mirror of the operator's.

    The only file the factory must put there is git identity. Every other file
    either does not exist or is something the agent CLI wrote itself from its
    own defaults. The negative assertion is what catches the shortcut: nothing
    under this home was copied from or derived from the operator's configuration.
    """
    write_control(stub_home_dir)

    await adapter.run_attempt(attempt(), factory_root=factory_root)

    seeded_files = {str(p.relative_to(stub_home_dir)) for p in stub_home_dir.rglob("*") if p.is_file()}
    # The factory pre-writes only .gitconfig; the stub writes its control file
    # and session transcript there during the attempt, which is the child writing,
    # not the factory copying from the operator.
    assert ".gitconfig" in seeded_files
    gitconfig = (stub_home_dir / ".gitconfig").read_text(encoding="utf-8")
    assert SALVAGE_AUTHOR_NAME in gitconfig
    assert SALVAGE_AUTHOR_EMAIL in gitconfig
    assert "oauthAccount" not in gitconfig
    assert "mcpServers" not in gitconfig
    assert "CLAUDE.md" not in seeded_files


async def test_the_seeding_function_never_reads_the_operator_home(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
) -> None:
    """The negative assertion that catches the copy-from-`~` shortcut (plan.md § US2).

    Even if the factory's per-node home is used as `HOME`, seeding it from the
    operator's `~/.claude.json` or `~/.claude/` would re-import exactly the
    surface this spec removes, `oauthAccount` included. The seeding function
    takes no path that could name the operator's home and produces only git
    identity from constants.
    """
    # Plant distinctive operator files the factory must not copy or read.
    (fake_home / ".claude.json").write_text(json.dumps({"oauthAccount": "operator"}), encoding="utf-8")
    (fake_home / ".claude").mkdir(parents=True)
    (fake_home / ".claude" / "CLAUDE.md").write_text("operator instructions", encoding="utf-8")
    (fake_home / ".gitconfig").write_text(
        "[user]\n  name = Operator\n  email = operator@example.com\n", encoding="utf-8"
    )
    write_control(stub_home_dir)

    await adapter.run_attempt(attempt(), factory_root=factory_root)

    seeded = {str(p.relative_to(stub_home_dir)) for p in stub_home_dir.rglob("*") if p.is_file()}
    assert ".gitconfig" in seeded
    gitconfig = (stub_home_dir / ".gitconfig").read_text(encoding="utf-8")
    assert "Operator" not in gitconfig
    assert "operator@example.com" not in gitconfig
    assert "oauthAccount" not in gitconfig
    assert "operator instructions" not in gitconfig
    # No factory file is a copy of an operator file byte-for-byte.
    operator_files = set(fake_home.rglob("*"))
    for seeded_path in (p for p in stub_home_dir.rglob("*") if p.is_file()):
        assert seeded_path not in operator_files, (
            f"{seeded_path} is byte-identical to a file in the operator's home"
        )


async def test_a_git_commit_in_the_child_environment_succeeds_with_factory_identity(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
) -> None:
    """FR-005: the agent's own commits carry the factory's salvage identity.

    A fresh factory-owned home has no `~/.gitconfig`, so a commit made inside
    the worktree under the child environment would fail with "Author identity
    unknown". The factory seeds git identity in the home; the commit then
    succeeds and is attributed to the same name and address salvage uses.
    """
    # Turn the plain worktree directory into a git repo, the way the agent finds it.
    subprocess.run(
        ["git", "init", "--quiet", "-b", "main"],
        cwd=str(worktree),
        capture_output=True,
        text=True,
        check=True,
        env={"HOME": str(fake_home), "GIT_CONFIG_GLOBAL": "/dev/null", "GIT_CONFIG_SYSTEM": "/dev/null", "PATH": os.environ["PATH"]},
    )
    write_control(stub_home_dir)

    env = attempt_env(attempt())
    env[ATTEMPT_ARCHIVE_ENV] = str(archive_dir(factory_root))
    result = await adapter.run_attempt(attempt(), factory_root=factory_root)
    assert result.termination == Termination.COMPLETED

    # Reaching in with the child environment, identity must come from the home.
    commit_result = git_commit_in_child_environment(worktree, stub_home_dir, env)
    assert commit_result.returncode == 0, (
        f"git commit failed: {commit_result.stderr}"
    )
    assert git_show_field(worktree, "%an") == SALVAGE_AUTHOR_NAME
    assert git_show_field(worktree, "%ae") == SALVAGE_AUTHOR_EMAIL
    assert git_show_field(worktree, "%cn") == SALVAGE_AUTHOR_NAME
    assert git_show_field(worktree, "%ce") == SALVAGE_AUTHOR_EMAIL


async def test_a_git_commit_fails_without_the_factory_seeded_identity(
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    fake_home: Path,
) -> None:
    """The control case: without the seeded home, the same commit cannot complete.

    The fixture sets up an unseeded home directory, then builds the child env
    exactly as the adapter would for that unseeded home. This proves the
    passing test above is due to the seeded identity, not to a git fall-back
    that happens to work in this test environment.
    """
    unseeded_home = home_path(factory_root, EPIC, "unseeded")
    unseeded_home.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        ["git", "init", "--quiet", "-b", "main"],
        cwd=str(worktree),
        capture_output=True,
        text=True,
        check=True,
        env={"HOME": str(unseeded_home), "GIT_CONFIG_GLOBAL": "/dev/null", "GIT_CONFIG_SYSTEM": "/dev/null", "PATH": os.environ["PATH"]},
    )

    env = attempt_env(
        attempt(home_path=str(unseeded_home)),
        {"PATH": os.environ["PATH"], "HOME": str(fake_home)},
    )
    env[ATTEMPT_ARCHIVE_ENV] = str(archive_dir(factory_root, ATTEMPT))

    commit_result = git_commit_in_child_environment(worktree, unseeded_home, env)
    assert commit_result.returncode != 0
    assert "Author identity unknown" in commit_result.stderr


async def test_the_archive_holds_both_artifacts_after_a_completed_attempt(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
    worktree: Path,
) -> None:
    """FR-006 / SC-002: the transcript directory contains the same two artifacts as before.

    Asserted by reading the directory, not by inspecting the path expression:
    the archive step resolves from the child's `HOME`, and the test proves the
    composition works end-to-end.
    """
    write_control(stub_home_dir)

    result = await adapter.run_attempt(attempt(), factory_root=factory_root)

    assert result.termination == Termination.COMPLETED
    archive = archive_dir(factory_root)
    assert archive.is_dir()
    assert (archive / STDOUT_LOG_NAME).is_file()
    assert (archive / f"{SESSION_ID}.jsonl").is_file()


async def test_an_attempt_that_wrote_no_transcript_still_archives_stdout_log(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
) -> None:
    """The missing-transcript path is normal, not an error; the log still survives."""
    write_control(stub_home_dir, write_transcript=False, exit_code=1)

    result = await adapter.run_attempt(attempt(), factory_root=factory_root)

    # Since 095-US1 the missing transcript is also the classification: no session
    # file means no turn ran. What this test is about — the log surviving anyway
    # — is unchanged, and matters more in this class than in any other.
    assert result.termination == Termination.PRE_AGENT_FAILURE
    archive = archive_dir(factory_root)
    assert (archive / STDOUT_LOG_NAME).is_file()
    assert not (archive / f"{SESSION_ID}.jsonl").exists()


async def test_the_archived_transcript_survives_the_home_directorys_removal(
    adapter: ClaudeCodeAdapter,
    attempt: Callable[..., AttemptContext],
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
    worktree: Path,
) -> None:
    """FR-006 / SC-005: once archived, evidence is independent of the home.

    The child wrote its session transcript under the factory-owned home; the
    adapter copied it into the archive directory. Removing the home afterwards
    proves the archive is complete and self-sufficient.
    """
    write_control(stub_home_dir)

    result = await adapter.run_attempt(attempt(), factory_root=factory_root)

    assert result.termination == Termination.COMPLETED
    archive = archive_dir(factory_root)
    archive_copy = archive / f"{SESSION_ID}.jsonl"
    assert archive_copy.is_file()
    before = archive_copy.read_bytes()

    import shutil
    shutil.rmtree(stub_home_dir)

    assert archive_copy.is_file()
    assert archive_copy.read_bytes() == before


# --- US4: the shared attempt policy, one implementation (FR-007) ----------------
#
# `ClaudeCodeAdapter.run_attempt` is mostly not about Claude. Pid file, orphan
# reap, archive directory, monitor loop, wall-clock deadline, operator-question
# ferry — none of that names a CLI, and a second adapter must not copy it. The
# hoist moves that policy into one implementation every adapter calls; what
# remains per-CLI is the narrow inner seam: argv, prompt delivery, provider env,
# home seeding, credential discovery, the turn-happened probe, refusal markers.
#
# The proof shape is the Independent Test: define a second adapter class that
# implements only the per-CLI concerns, run an attempt through it, and read
# which parts of attempt policy it did not write. The stub `claude` serves as
# the second CLI: its transcript convention already matches, so the per-CLI
# surface it needs is exactly the surface the seam exposes.


class SecondCliAdapter:
    """A second adapter implementing ONLY the per-CLI concerns (US4-S1).

    Every agent-agnostic piece of attempt policy is absent here — its class
    body is the proof: the assertions below read this source and fail if any
    of it appears in the class.
    """

    name = "second-cli"

    def __init__(self) -> None:
        self.executable = str(STUB_AGENT_PATH)
        self.grace_s = TEST_GRACE_S
        self._backend: Any = HostAgentBackend(executable=str(STUB_AGENT_PATH))

    async def run_attempt(
        self,
        context: AttemptContext,
        *,
        factory_root: Path | str,
        **kwargs: Any,
    ) -> AdapterResult:
        """Delegate to the shared policy — the one implementation."""
        return await SharedAttemptPolicy(self).run_attempt(
            context,
            factory_root=factory_root,
            **kwargs,
        )

    # -- the per-CLI surface, and nothing else --------------------------------

    def _argv(self, context: AttemptContext) -> list[str]:
        return [self.executable, "--session-id", context.session_id]

    def _provider_env(self, env: dict[str, str], context: AttemptContext) -> dict[str, str]:
        """The CLI's own variables on top of the attempt's, nothing inherited."""
        env["SECOND_CLI_CONTROL"] = "on"
        return env

    async def _deliver_prompt(self, process: Any, prompt: str) -> None:
        await _feed_prompt(process, prompt)

    def _credential(self, context: AttemptContext) -> CredentialStage:
        """Gateway persona: no subscription credential to discover."""
        return CredentialStage(gateway=True)

    def _seed_home(self, home: Path, credential_path: Path | None) -> None:
        """The second CLI starts from a bare home: nothing to seed."""
        return None

    def _turn_happened(self, context: AttemptContext, worktree: Path, env: Mapping[str, str]) -> bool:
        """The structural tell, as this CLI writes it."""
        return _second_cli_wrote_transcript(context, worktree, env)

    def _refusal_markers(self) -> tuple[str, ...]:
        return ("SECOND-CLI REFUSED",)


def _second_cli_wrote_transcript(
    context: AttemptContext, worktree: Path, env: Mapping[str, str]
) -> bool:
    """The turn probe for the second CLI: same convention the stub honours."""
    home = env.get("HOME")
    if not home:
        return True
    transcript = (
        Path(home) / ".claude" / "projects" / _second_cli_dir_name(worktree)
        / f"{context.session_id}.jsonl"
    )
    return transcript.is_file()


def _second_cli_dir_name(cwd: Path) -> str:
    import re

    return re.sub(r"[^a-zA-Z0-9]", "-", str(Path(cwd).resolve()))


@pytest.fixture
def second_adapter() -> SecondCliAdapter:
    """The second adapter, pointed at the same stub the first one uses."""
    return SecondCliAdapter()


@pytest.fixture
def second_registered(monkeypatch: pytest.MonkeyPatch) -> None:
    """Register the second adapter, the way spec 155's will be."""
    monkeypatch.setitem(_ADAPTERS, SecondCliAdapter.name, SecondCliAdapter)


# The shared policy must exist and be shared — a name the tests can import and
# both classes call. Written before the implementation (constitution II); the
# import at the top of this file fails on the tree as received.


def test_the_outer_protocol_is_one_method_still() -> None:
    """US4-S2: the hoist does not resurrect the five-method protocol that
    specs/005-workgraph-interpreter/contracts/adapter.md sketched and the
    implementation deliberately collapsed. `AgentAdapter` declares one method —
    `run_attempt` — and the inner seam the hoist introduces is private to the
    module, not a widening of what orchestration sees."""
    protocol_methods = {
        name
        for name, value in vars(AgentAdapter).items()
        if not name.startswith("_") and callable(value)
    }
    assert protocol_methods == {"run_attempt"}, (
        f"the AgentAdapter protocol declares {sorted(protocol_methods)}; the outer "
        "protocol stays one method (US4-S2)"
    )
    # The hoist's seam is the per-CLI surface, carried by a separate private
    # collaboration — never by the protocol orchestration resolves through.
    assert not hasattr(AgentAdapter, "argv")
    assert not hasattr(AgentAdapter, "deliver_prompt")
    assert not hasattr(AgentAdapter, "provider_env")
    assert not hasattr(AgentAdapter, "credential")
    assert not hasattr(AgentAdapter, "turn_happened")
    assert not hasattr(AgentAdapter, "refusal_markers")


async def test_the_second_adapter_runs_the_shared_policy_end_to_end(
    second_adapter: SecondCliAdapter,
    second_registered: None,
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
) -> None:
    """US4-S1: an attempt through the second adapter gets the whole shared
    policy — pid file written and cleared, archive populated, deadline ended,
    orphan reaped — from the one implementation, and the second class wrote
    none of it."""
    write_control(stub_home_dir)

    result = await second_adapter.run_attempt(
        attempt(agent="second-cli"), factory_root=factory_root
    )

    # The archive is the shared policy's (FR-007): stdout.log beside the
    # session transcript, in the attempt directory the shared naming derives.
    assert result.termination == Termination.COMPLETED
    archive = archive_dir(factory_root)
    assert (archive / STDOUT_LOG_NAME).is_file()
    assert (archive / f"{SESSION_ID}.jsonl").is_file()
    # The pid file was written for this attempt's group and cleared on exit.
    assert not pid_file(factory_root, EPIC, NODE).exists()
    # The env the child received is the shared construction: HOME is the
    # factory's per-node home, ATTEMPT_ARCHIVE names the archive directory,
    # and the per-CLI provider variables ride on top.
    invocation = last_invocation(worktree)
    assert invocation.env["HOME"] == str(stub_home_dir)
    assert invocation.env[ATTEMPT_ARCHIVE_ENV] == str(archive)
    assert invocation.env["SECOND_CLI_CONTROL"] == "on"


async def test_the_second_adapter_ends_its_process_tree_at_the_deadline(
    second_adapter: SecondCliAdapter,
    second_registered: None,
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
) -> None:
    """US4-S1, the deadline half: the second adapter inherits the wall-clock
    deadline and the process-group termination — TERM to the group, KILL past
    the grace — without writing any of it."""
    write_control(
        stub_home_dir, sleep_s=300.0, ignore_sigterm=True, spawn_child=True, child_sleep_s=300.0
    )

    result = await second_adapter.run_attempt(
        attempt(agent="second-cli", timeout_s=DEADLINE_S),
        factory_root=factory_root,
    )

    assert result.termination == Termination.TIMEOUT
    invocation = last_invocation(worktree)
    assert any(entry.startswith("TERM") for entry in invocation.signals), (
        f"the group was never TERM'd: {invocation.signals}"
    )
    # A run that ignored TERM and still ended can only have ended on KILL —
    # observed on the grandchild, which only the group signal can reach.
    grandchild = invocation.child_pid
    assert grandchild is not None
    await wait_until(
        lambda: not pid_alive(grandchild), what="the agent's child to be killed too"
    )


async def test_the_second_adapter_reaps_a_previous_runs_orphan(
    second_adapter: SecondCliAdapter,
    second_registered: None,
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
    spawn_orphan: Callable[[], subprocess.Popen[bytes]],
) -> None:
    """US4-S1, the reap half: the orphan a dead worker left behind is ended
    before the second adapter's own launch — the same shared precaution."""
    orphan = spawn_orphan()
    plant_pid_file(factory_root, f"{orphan.pid}\n")
    write_control(stub_home_dir, sleep_s=2.0)

    run = asyncio.create_task(
        second_adapter.run_attempt(
            attempt(agent="second-cli"), factory_root=factory_root
        )
    )
    try:
        await wait_until(lambda: stub_is_up(worktree), what="the second CLI to launch")
        assert orphan.poll() is not None, "the orphan was still alive at relaunch"
    finally:
        result = await run

    assert result.termination == Termination.COMPLETED
    assert orphan.wait(timeout=PATIENCE_S) in (-signal.SIGTERM, -signal.SIGKILL)


async def test_the_second_adapter_ferries_an_operator_question(
    second_adapter: SecondCliAdapter,
    second_registered: None,
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    fake_home: Path,
    stub_home_dir: Path,
) -> None:
    """US4-S1, the ferry half: the monitor loop that watches the archive
    directory, ships the question up and the answer down is the shared one —
    the second adapter wired none of it."""
    write_control(stub_home_dir, ferry_question=FERRY_QUESTION, ferry_window_s=3.0)
    shipped: list[str] = []

    async def send_ferry_question(text: str) -> str:
        shipped.append(text)
        return "q-ferried"

    run = asyncio.create_task(
        second_adapter.run_attempt(
            attempt(agent="second-cli"),
            factory_root=factory_root,
            send_ferry_question=send_ferry_question,
        )
    )
    await _wait_for_question(factory_root)
    # The monitor ships the question up on a beat, not at file-appearance, so
    # the answer waits until the ship is observed — answering first would end
    # the stub inside its 1s first beat and the ship would never run.
    await wait_until(lambda: len(shipped) >= 1, what="the question to ship up")
    _write_answer(factory_root, FERRY_ANSWER)
    result = await run

    assert shipped == [FERRY_QUESTION], f"the question shipped {len(shipped)} times"
    assert result.termination == Termination.COMPLETED


def test_the_second_class_contains_none_of_the_shared_policy() -> None:
    """US4-S1, read off the class itself: the second adapter's source names no
    pid file, no orphan reap, no archive step, no monitor loop, no deadline, no
    ferry. The shared policy is the one implementation both call, and this is
    the 'proven by the second class containing none of it' half."""
    source = inspect.getsource(SecondCliAdapter)
    lowered = source.lower()
    for spelled in (
        "pid_file",
        "pidfile",
        "reap",
        "killpg",
        "signal_group",
        "archive_session",
        "stdout_log_name",
        "monitor",
        "ferry",
        "wait_for",
        "timeout_s",
        "transcript_dir",
        "preserve_previous_stdout",
        "heartbeat",
        "read_usage",
        "send_ferry",
        "read_ferry",
    ):
        assert spelled not in lowered, (
            f"the second adapter spells {spelled!r}; that is the shared policy, "
            "and a second copy of it is the defect US4 exists to prevent"
        )


def test_the_per_cli_surface_is_all_the_shared_policy_takes() -> None:
    """FR-007's seam, spelled as names: the per-CLI surface an adapter supplies
    is argv, prompt delivery, provider env, home seeding, credential discovery,
    the turn-happened probe, and refusal markers — and nothing wider."""
    surface = {
        name
        for name, value in vars(SecondCliAdapter).items()
        if not name.startswith("__") and callable(value)
    }
    assert surface == {
        "run_attempt",
        "_argv",
        "_provider_env",
        "_deliver_prompt",
        "_credential",
        "_seed_home",
        "_turn_happened",
        "_refusal_markers",
    }, f"the per-CLI seam grew {sorted(surface - {'run_attempt'})} or shrank"
