"""US3 of epic 130: the detector carries no language-shaped list.

The detector used to carry two module constants — a directory-name set and a
file-suffix tuple — that decided, in *this* repository, what counts as generated
output in someone else's. 073 added them so a concurrent sibling's test run
would not fill the runtime-root snapshot; 130-US2 then stopped the walk from
visiting node worktrees at all, which left `_snapshot_paths` — the only
consumer of those constants — unreferenced (plan trap 10 kept all three in
place for this story). This story deletes them, and FR-006 forbids replacing
them: no ignore-rule parser, no `git check-ignore` call, no new dependency.
The surviving rule is the one the target repository already applies — git's own
`--exclude-standard`, read in the target by `_tracked_state`.

After US2 the runtime-root half of the comparison looks at exactly the three
named evidence stores, and the target-repo half defers to the target's rules,
so there is nothing left for a list to prune. A list that grew back could only
decide what a *language this floor never tested against* may write — which is
the shape of the original defect, in the one place it is hardest to see.

The two controls are the point (spec US3-S2: "This scenario is a control"):

- **US3-S2** is green before this story and must stay green through the
  removal: a target whose own `.gitignore` covers a generated directory
  silences writes into it, because the target's rules — not any list here —
  keep those paths out of the comparison. The fixture directory is deliberately
  `node_modules/`, which ergane's own `.gitignore` does NOT cover (`__pycache__`
  and `.pytest_cache` are on this floor's list): a detector that read the
  host's rules instead of the target's would pass on this floor and fail on
  every consumer, and this fixture is what catches it (trap 8).
- **US3-S3** is the same fixture with the `.gitignore` line withdrawn: the
  same writes file a finding. Ignoring is the target's statement, not the
  detector's guess.

These tests drive the detector directly through `capture_start` and
`compare_and_report` against a `tmp_path` runtime root, the pattern
`tests/test_detector_reports_removals_only.py` established.
"""

from __future__ import annotations

import re
import tomllib
from pathlib import Path
from typing import Callable

import pytest

from factory.doctor.models import Severity
from factory.workgraph.detector import capture_start, compare_and_report
from factory.workgraph.models import AttemptContext
from tests.target_repo import git

EPIC = "130-the-boundary-detector-charges-an-attempt-only-for-what-it-wrote"
NODE = "us3"
ATTEMPT = 1

#: A generated directory a JavaScript target ignores. Deliberately NOT one
#: ergane's own `.gitignore` covers — `__pycache__/` and `.pytest_cache/` are
#: on this floor's list — so the control cannot pass by reading the host's
#: rules instead of the target's (trap 8).
GENERATED_DIR = "node_modules"

#: Files an attempt writes into the generated directory, outside its worktree.
GENERATED_WRITES = (
    f"{GENERATED_DIR}/left-pad/index.js",
    f"{GENERATED_DIR}/left-pad/package.json",
)

#: The target's own ignore rule, as a real JS target declares one: a committed
#: line, not a detector constant. Withdrawn again by US3-S3.
IGNORE_COMMENT = "# build output, generated by installs — the target's statement"
IGNORE_LINE = f"{GENERATED_DIR}/"


@pytest.fixture
def runtime_root(tmp_path: Path) -> Path:
    """A supplied runtime root with all three evidence stores populated."""
    root = tmp_path / ".ergane"
    root.mkdir()
    for name in ("doctor.db", "ledger.db", "verification.db"):
        (root / name).write_text(f"initial {name} content\n", encoding="utf-8")
    return root


@pytest.fixture
def own_worktree(tmp_path: Path) -> Path:
    """Where this attempt's agent runs; it is allowed to write here."""
    path = tmp_path / "own-worktree"
    path.mkdir()
    return path


@pytest.fixture
def repo(target_repo: Callable[..., Path]) -> Path:
    """A real target repository, clean at attempt start."""
    return target_repo("passing")


@pytest.fixture
def context(repo: Path, own_worktree: Path) -> AttemptContext:
    return AttemptContext(
        epic_id=EPIC,
        node_id=NODE,
        attempt=ATTEMPT,
        prompt="Implement US3.\n",
        worktree_path=str(own_worktree),
        home_path=str(own_worktree / "home"),
        proxy_url="http://litellm.test:4000",
        virtual_key="sk-virtual-130-us3-1",
        model_alias="anthropic/CHANGEME",
        session_id="0f2c9a71-5d48-4c3b-8a6e-2b7c1d0e9f43",
        timeout_s=60,
        target_repo=str(repo),
    )


@pytest.fixture
def attempt(
    runtime_root: Path, repo: Path, context: AttemptContext
) -> Callable[[Callable[[], None]], object]:
    """Run one attempt: capture, let `during` happen, compare.

    Returns whatever `compare_and_report` returns — the finding, or `None` for
    silence.
    """

    def run(during: Callable[[], None]):
        capture_start(runtime_root, repo, context)
        during()
        return compare_and_report(runtime_root, repo, context)

    return run


# --- fixture helpers ---------------------------------------------------------


def _target_declares_ignore(repo: Path) -> None:
    """Give the target repository its own ignore rule, committed.

    The rule is the target's statement, declared the way a real JavaScript
    target declares one: a line in its own `.gitignore`, committed before the
    attempt starts so the start snapshot sees the same rules git applies.
    """
    gitignore = repo / ".gitignore"
    gitignore.write_text(
        gitignore.read_text(encoding="utf-8") + f"\n{IGNORE_COMMENT}\n{IGNORE_LINE}\n",
        encoding="utf-8",
    )
    git(repo, "add", ".gitignore")
    git(repo, "commit", "--quiet", "-m", "target: ignore the generated build directory")


def _target_withdraws_ignore(repo: Path) -> None:
    """Remove that line again and commit the withdrawal — US3-S3's fixture."""
    gitignore = repo / ".gitignore"
    text = gitignore.read_text(encoding="utf-8")
    suffix = f"\n{IGNORE_COMMENT}\n{IGNORE_LINE}\n"
    assert text.endswith(suffix), (
        "fixture premise broken: the ignore block US3-S3 withdraws is not present"
    )
    gitignore.write_text(text[: -len(suffix)], encoding="utf-8")
    git(repo, "add", ".gitignore")
    git(repo, "commit", "--quiet", "-m", "target: stop ignoring the generated directory")


def _write_generated_files(repo: Path) -> None:
    """The escape under test: an attempt writing into the target, not its worktree."""
    for rel in GENERATED_WRITES:
        path = repo / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("module.exports = 1;\n", encoding="utf-8")


def _untracked_in_target(repo: Path) -> list[str]:
    """What git itself lists as untracked-not-ignored, read in the target repo."""
    return git(repo, "ls-files", "--others", "--exclude-standard").splitlines()


# --- T015 / US3-S1: no generated-path list, and nothing replaced it ----------


def test_detector_defines_no_generated_path_exclusion_list() -> None:
    """US3-S1 / FR-006: the names are gone from the module, and nothing replaced them.

    Written first and observed red against the pre-story module, which still
    defined all three names — US2 left them unreferenced on purpose (plan
    trap 10), and this is the test the removal has to earn.
    """
    import factory.workgraph.detector as detector

    defined = set(vars(detector))
    for name in ("EXCLUDED_DIR_NAMES", "EXCLUDED_SUFFIXES", "_snapshot_paths"):
        assert name not in defined, (
            f"{name} is a language-shaped list in the detector; FR-006 removed it "
            "and it must not come back"
        )

    # No ignore-rule parser replaced them: the module neither reads an ignore
    # file, asks git what it ignores, nor imports a parser library (trap 8).
    source = Path(detector.__file__).read_text(encoding="utf-8")
    for machinery in (".gitignore", "check-ignore", "pathspec"):
        assert machinery not in source, (
            f"an ignore-rule parser ({machinery}) must not replace the removed list"
        )

    # And the surviving rule is the one FR-006 names: the target repository's
    # own ignore rules, which git applies in the target when `_tracked_state`
    # reads untracked files.
    assert "--exclude-standard" in source, (
        "the surviving rule must be the target's own ignore rules, read by "
        "_tracked_state through git's --exclude-standard"
    )


def test_no_ignore_rule_parser_dependency_was_added() -> None:
    """US3-S1 / FR-006: no dependency arrived to do the list's job (trap 8).

    `.gitignore` parsing has a canonical package name, and the constitution
    requires operator approval for any new dependency anyway (III); if the
    list's job came back as a library, this is where it would show.
    """
    pyproject = Path(__file__).resolve().parents[1] / "pyproject.toml"
    data = tomllib.loads(pyproject.read_text(encoding="utf-8"))

    declared: list[str] = list(data["project"]["dependencies"])
    declared += list(data["project"].get("optional-dependencies", {}).values())
    declared += list(data["dependency-groups"]["dev"])

    names = [re.split(r"[\s\[<>=!~;]", dep, maxsplit=1)[0].strip().lower() for dep in declared]
    assert names, "fixture premise broken: no declared dependencies found"
    for name in names:
        assert "ignore" not in name and name != "pathspec", (
            f"{name} looks like an ignore-rule parser standing in for the removed "
            "list; FR-006 forbids it and constitution III forbids the dependency"
        )


# --- T016 / US3-S2: the control — the target's own rules keep it silent ------


def test_target_ignoring_generated_dir_keeps_writes_silent(
    runtime_root: Path,
    repo: Path,
    attempt: Callable[[Callable[[], None]], object],
) -> None:
    """US3-S2 / FR-006 (control): the target's `.gitignore` is the surviving rule.

    Green before this story — `_tracked_state` reads untracked files with
    `--exclude-standard` in the target repository, so paths the target ignores
    are absent from the teardown snapshot and can never be charged to the
    attempt — and its job is to stay green through the removal of the list.
    The fixture premise is asserted with git, in the target repository, never
    with anything the detector reads.
    """
    _target_declares_ignore(repo)

    finding = attempt(lambda: _write_generated_files(repo))

    # Fixture premise: the target's own rules really do cover what was written.
    untracked = _untracked_in_target(repo)
    assert not [path for path in untracked if path.startswith(f"{GENERATED_DIR}/")], (
        "fixture premise broken: the target's ignore rules no longer cover the "
        "generated directory"
    )
    # The writes happened, and the detector is read-only with respect to them.
    for rel in GENERATED_WRITES:
        assert (repo / rel).exists()
    assert finding is None, (
        "a write into a directory the *target* ignores is the target's statement, "
        "not an escape"
    )


# --- T017 / US3-S3: the control — without the target's rule, it files --------


def test_target_not_ignoring_generated_dir_files_a_finding(
    runtime_root: Path,
    repo: Path,
    attempt: Callable[[Callable[[], None]], object],
) -> None:
    """US3-S3 / FR-006 (control): the same writes file once the rule is withdrawn.

    The same fixture with the `.gitignore` line removed and the removal
    committed: the writes now appear as untracked-not-ignored paths in the
    teardown snapshot and file the tracked half's finding. This is the silence
    US3-S2 must not take with it — a detector that went silent everywhere
    would pass both controls, and this one is what stops that.
    """
    _target_declares_ignore(repo)
    _target_withdraws_ignore(repo)

    finding = attempt(lambda: _write_generated_files(repo))

    # Fixture premise: without the line, git itself lists the writes.
    untracked = _untracked_in_target(repo)
    for rel in GENERATED_WRITES:
        assert rel in untracked, f"fixture premise broken: {rel} is still ignored"

    assert finding is not None, (
        "the same write, with the target's rule withdrawn, must file a finding"
    )
    assert finding.severity is Severity.CRITICAL
    for rel in GENERATED_WRITES:
        assert f"target:{rel}" in finding.refs
    # Nothing under the runtime root was lost, so the finding is the tracked
    # half alone.
    assert not [ref for ref in finding.refs if ref.startswith("runtime:")]
    # The detector is read-only: it reports the escape, it does not undo it.
    for rel in GENERATED_WRITES:
        assert (repo / rel).exists()