"""US1 of 155: a Codex node runs on the gateway, driving an ollama-cloud alias.

A persona names `agent: codex` and `route: gateway`; the attempt runs Codex
against the same LiteLLM aliases the ladder already uses, spend attributed to
the attempt's virtual key exactly as Claude's is. Like `test_adapter.py`, these
tests launch a real child — `tests/stub_codex.py` standing in for the CLI — and
read back what it recorded, because what a second adapter does is only
observable from inside the child.

The scenarios, entry for entry:

- **US1-S1** (FR-001, FR-004): the launched process is `codex exec` with the
  prompt on stdin — `codex exec -` plus the model alias and the sandbox/cd
  flags — and a persona naming `agent: codex` resolves the registered adapter.
- **US1-S2** (FR-002): the spend is read from the proxy on the attempt's
  virtual key, exactly as a Claude gateway attempt's is — the same
  `read_usage` seam, wired to the same key the context carries. Token
  accounting is NOT a reason to add `--json`.
- **US1-S3** (FR-003): the adapter seeds a per-node `CODEX_HOME` whose
  generated `config.toml` declares the gateway as a custom provider
  (`model_provider`, `[model_providers.ergane-gateway]` with `base_url`,
  `env_key`, `wire_api`) parameterised by the attempt's proxy URL and virtual
  key — the analogue of `_seed_node_home`, not a copy.
- **US1-S4** (FR-007, trap 1): reasoning-model chain-of-thought returned in
  cleartext (P1 measured) does not misclassify the run — the turn probe and
  the classification read structural facts (files, exit status), never the
  text the model produced, so reasoning text near the output satisfies and
  defeats nothing.

Written before `CodexAdapter` exists (constitution II): on the tree as
received, every test here fails — there is no `codex` entry in `_ADAPTERS`
and no adapter class to launch.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any, Callable

import pytest

from factory.usage.models import Termination
from factory.workgraph.adapter import (
    ATTEMPT_ARCHIVE_ENV,
    STDOUT_LOG_NAME,
    AdapterError,
    HostAgentBackend,
    _ADAPTERS,
    adapter_for,
    attempt_env,
    home_path,
    transcript_dir,
)
from factory.workgraph.models import AdapterResult, AttemptContext
from tests.stub_codex import (
    BANNER,
    CODEX_GATEWAY_KEY,
    CODEX_HOME_ENV,
    REFUSAL_MARKER,
    STUB_CODEX_PATH,
    codex_home,
    install_as,
    last_invocation,
    rollout_path,
    write_control,
)

EPIC = "155-codex-runs-as-a-second-runner"
NODE = "us1"

#: Not 1: the attempt number names the archive directory, and an off-by-one
#: that always wrote `attempt-1` would pass every test that ran one attempt.
ATTEMPT = 2

#: Generated by the workflow with `workflow.uuid4()` (R6) — but a Codex attempt
#: has no `--session-id` flag (trap 4, measured), so the id travels in the
#: context and is used for archive identity, never as a CLI argument.
SESSION_ID = "9b1f5d4e-3a2c-4f80-9c1a-7e6d5b4a3c99"

#: A LiteLLM alias as `personas.yaml` writes them. Travels from the registry
#: to argv untouched — no code here names a model (constitution VII).
MODEL_ALIAS = "ollama-cloud/glm-5.3-flash"

PROXY_URL = "http://litellm.test:4000"
VIRTUAL_KEY = "sk-virtual-155-codex-runs-as-a-second-runner-us1-2"

PROMPT = "You are the implementer persona.\n\n## Scope\n\nImplement US1.\n"

#: Long enough that no test races its deadline; the production value is the
#: persona registry's (FR-010).
GENEROUS_TIMEOUT_S = 60


# --- setup -------------------------------------------------------------------


@pytest.fixture
def codex_bin(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """`tests/stub_codex.py` where `codex` would be found (R6).

    Nothing configures the agent binary in production — the persona's `agent`
    field selects a class, and that class runs `codex` off the passed-through
    `PATH` — so the tests do not configure it either.
    """
    bin_dir = tmp_path / "bin"
    install_as(bin_dir, "codex")
    monkeypatch.setenv("PATH", f"{bin_dir}{os.pathsep}{os.environ['PATH']}")
    return bin_dir


@pytest.fixture
def worktree(tmp_path: Path) -> Path:
    """Where the agent runs. A directory, not a repository — the adapter's
    contract is "cwd is the path you were handed"."""
    path = tmp_path / "worktrees" / EPIC / NODE
    path.mkdir(parents=True)
    return path


@pytest.fixture
def factory_root(tmp_path: Path) -> Path:
    """The worker host's state directory: transcripts, pid files."""
    return tmp_path / ".factory"


@pytest.fixture
def node_home(factory_root: Path) -> Path:
    """The factory's per-node home — the parent of the seeded CODEX_HOME."""
    return home_path(factory_root, EPIC, NODE)


@pytest.fixture
def attempt(worktree: Path, node_home: Path) -> Callable[..., AttemptContext]:
    """Build the attempt's context; `attempt(attempt=3)` overrides one field."""

    def build(**overrides: Any) -> AttemptContext:
        fields: dict[str, Any] = {
            "epic_id": EPIC,
            "node_id": NODE,
            "attempt": ATTEMPT,
            "prompt": PROMPT,
            "worktree_path": str(worktree),
            "home_path": str(node_home),
            "proxy_url": PROXY_URL,
            "virtual_key": VIRTUAL_KEY,
            "model_alias": MODEL_ALIAS,
            "session_id": SESSION_ID,
            "timeout_s": GENEROUS_TIMEOUT_S,
            "agent": "codex",
            "route": "gateway",
        }
        return AttemptContext(**(fields | overrides))

    return build


@pytest.fixture
def adapter(node_home: Path) -> Any:
    """The Codex adapter, pointed at the stub instead of `codex`.

    Registered in the real `_ADAPTERS` under its own name (FR-001) and resolved
    through `adapter_for` — selection by persona value is 154's contract, and
    this suite would not notice the registry entry being bypassed if it built
    the class by hand.
    """
    from factory.workgraph.adapter import CodexAdapter

    return CodexAdapter(
        executable=str(STUB_CODEX_PATH),
        grace_s=0.4,
        backend=HostAgentBackend(executable=str(STUB_CODEX_PATH)),
    )


@pytest.fixture(autouse=True)
def worker_env(monkeypatch: pytest.MonkeyPatch) -> None:
    """A worker host's environment: credentials, locale, ordinary clutter.

    The credentials are planted for every test: the allowlist's promise is
    that no launch anywhere can carry them.
    """
    monkeypatch.setenv("LITELLM_MASTER_KEY", "sk-master-must-never-reach-an-agent")
    monkeypatch.setenv("TELEGRAM_BOT_TOKEN", "1234567:telegram-bot-token-must-never-reach-an-agent")
    monkeypatch.setenv("LANG", "en_US.UTF-8")
    monkeypatch.setenv("TERM", "dumb")


def archive_dir(factory_root: Path, attempt_number: int = ATTEMPT) -> Path:
    return transcript_dir(factory_root, EPIC, NODE, attempt_number)


def stdout_log(factory_root: Path) -> str:
    return (archive_dir(factory_root) / STDOUT_LOG_NAME).read_text(encoding="utf-8")


# --- US1-S1: the launch (FR-001, FR-004) ---------------------------------------


def test_a_persona_naming_codex_resolves_the_registered_adapter() -> None:
    """FR-001: `codex` is in `_ADAPTERS`, and `adapter_for` resolves it by its
    own name — 154's unknown-agent refusal must NOT fire for it."""
    assert "codex" in _ADAPTERS
    resolved = adapter_for("codex")
    assert type(resolved).__name__ == "CodexAdapter"
    assert resolved.name == "codex"


async def test_the_launch_is_codex_exec_with_the_prompt_on_stdin(
    adapter: Any,
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    node_home: Path,
) -> None:
    """US1-S1 / FR-004: `codex exec -` — prompt on stdin, not argv — with the
    model alias, the sandbox bypass and the worktree cd in argv, running in the
    node worktree."""
    write_control(node_home)

    result = await adapter.run_attempt(attempt(), factory_root=factory_root)

    assert result.termination == Termination.COMPLETED
    launch = last_invocation(worktree)
    argv = launch["argv"]
    assert Path(argv[0]).name == "codex"
    assert "exec" in argv
    # The trailing `-` is what puts the prompt on stdin (measured: without it,
    # or with empty stdin, the CLI refuses with "No prompt provided via
    # stdin.").
    assert argv[-1] == "-"
    assert "--model" in argv
    assert argv[argv.index("--model") + 1] == MODEL_ALIAS
    # Codex's own read-only default must not stack on top of the factory's
    # boundary (US4-S2's rule, applied here where the bypass is chosen).
    assert "--dangerously-bypass-approvals-and-sandbox" in argv
    # The worktree is the agent's working root, by flag and by cwd.
    assert "--cd" in argv
    assert argv[argv.index("--cd") + 1] == str(worktree)
    assert launch["cwd"] == str(worktree)
    # The prompt arrives on stdin, whole, not on the command line.
    assert launch["stdin"] == PROMPT
    assert PROMPT not in " ".join(argv)
    # No session-id flag exists for Codex (trap 4, measured): the workflow's
    # id must not be smuggled onto argv.
    assert "--session-id" not in argv
    assert SESSION_ID not in " ".join(argv)


async def test_the_child_environment_is_the_built_allowlist_plus_codex_names(
    adapter: Any,
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    node_home: Path,
) -> None:
    """FR-002: the gateway env points at the attempt's virtual key via the
    `env_key` the generated config names, and the home is the seeded per-node
    CODEX_HOME. The allowlist is still closed: no master key, no bot token."""
    write_control(node_home)

    await adapter.run_attempt(attempt(), factory_root=factory_root)

    env = last_invocation(worktree)["env"]
    assert env[CODEX_GATEWAY_KEY] == VIRTUAL_KEY
    assert env[CODEX_HOME_ENV] == str(codex_home(node_home))
    assert env["HOME"] == str(node_home)
    assert "LITELLM_MASTER_KEY" not in env
    assert "TELEGRAM_BOT_TOKEN" not in env
    # Claude's variables are Claude's: a Codex launch carries the key under
    # its own env_key name, not under ANTHROPIC_AUTH_TOKEN.
    assert "ANTHROPIC_AUTH_TOKEN" not in env
    # The archive directory is still the ferry channel (008-US3).
    assert env[ATTEMPT_ARCHIVE_ENV] == str(archive_dir(factory_root))


async def test_no_worker_credential_reaches_the_codex_agent(
    adapter: Any,
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    node_home: Path,
) -> None:
    """US2-S1's promise, held for the second adapter too: by omission, not
    redaction — the values are checked, not just their names."""
    write_control(node_home)

    await adapter.run_attempt(attempt(), factory_root=factory_root)

    env = last_invocation(worktree)["env"]
    assert "sk-master-must-never-reach-an-agent" not in json_env(env)
    assert "telegram-bot-token-must-never-reach-an-agent" not in json_env(env)


def json_env(env: dict[str, str]) -> str:
    import json

    return json.dumps(env)


# --- US1-S2: spend on the attempt's virtual key (FR-002) -----------------------


async def test_the_spend_is_read_on_the_attempts_virtual_key(
    adapter: Any,
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    node_home: Path,
) -> None:
    """US1-S2 / FR-002: spend rides the adapter's `read_usage` seam, and the
    snapshot it returns rides home on the result. Token accounting is NOT a
    reason to add `--json` — the launched argv carries none."""
    write_control(node_home)
    keys_read: list[str | None] = []

    async def read_usage() -> Any:
        keys_read.append("read")
        return None

    result = await adapter.run_attempt(
        attempt(), factory_root=factory_root, read_usage=read_usage
    )

    assert result.termination == Termination.COMPLETED
    assert keys_read, "the attempt never read spend on its own key"
    # And the argv it launched carries no --json: accounting comes from the
    # proxy on the key, never from the CLI's output stream.
    launch = last_invocation(worktree)
    assert "--json" not in launch["argv"]


async def test_the_spends_snapshot_rides_home_on_the_result(
    adapter: Any,
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    node_home: Path,
) -> None:
    """FR-002, the other half: the newest reading the monitor carries is the
    result's `last_snapshot` — the same channel a Claude gateway attempt uses,
    so the ledger row is attributable to the same key either way."""
    from factory.usage.models import UsageSnapshot

    write_control(node_home)
    snapshot = UsageSnapshot(spend_usd=0.42, captured_at="2026-09-08T00:00:00Z")
    calls: list[int] = []

    async def read_usage() -> UsageSnapshot:
        calls.append(1)
        return snapshot

    result = await adapter.run_attempt(
        attempt(), factory_root=factory_root, read_usage=read_usage
    )

    assert result.termination == Termination.COMPLETED
    assert calls, "the spend read never ran"
    assert result.last_snapshot == snapshot


# --- US1-S3: the generated config.toml (FR-003) --------------------------------


async def test_the_seeded_codex_home_declares_the_gateway_provider(
    adapter: Any,
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    node_home: Path,
) -> None:
    """US1-S3 / FR-003: a generated `config.toml` in the per-node CODEX_HOME
    declares the gateway as a custom provider, parameterised by the attempt's
    proxy URL and key — the analogue of `_seed_node_home`, not a copy."""
    write_control(node_home)

    await adapter.run_attempt(attempt(), factory_root=factory_root)

    config = (codex_home(node_home) / "config.toml").read_text(encoding="utf-8")
    assert 'model_provider = "ergane-gateway"' in config
    assert "[model_providers.ergane-gateway]" in config
    assert f'base_url = "{PROXY_URL}/v1"' in config
    assert f'env_key = "{CODEX_GATEWAY_KEY}"' in config
    assert 'wire_api = "responses"' in config
    # The provider block does not embed the key value — the key travels in the
    # env the env_key names, so it is not written to disk twice.
    assert VIRTUAL_KEY not in config
    # The alias is the persona's; the config names no model of its own.
    assert "ollama-cloud" not in config


async def test_the_seeded_config_is_per_node_and_survives_a_second_attempt(
    adapter: Any,
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    node_home: Path,
) -> None:
    """FR-003: per-node, not per-attempt — a retry re-seeds the same home, and
    the file it finds is complete (no half-written config from a killed run)."""
    write_control(node_home)
    first = await adapter.run_attempt(attempt(attempt=1), factory_root=factory_root)
    assert first.termination == Termination.COMPLETED

    write_control(node_home, exit_code=1)
    second = await adapter.run_attempt(attempt(attempt=2), factory_root=factory_root)

    assert second.termination == Termination.AGENT_ERROR
    config = (codex_home(node_home) / "config.toml").read_text(encoding="utf-8")
    assert "[model_providers.ergane-gateway]" in config


# --- the home (FR-003, per-node identity) ---------------------------------------


async def test_the_seeded_home_keeps_the_factory_git_identity(
    adapter: Any,
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    node_home: Path,
) -> None:
    """The per-node home still carries the git identity the salvage path
    attributes commits to (FR-005) — a Codex node's commits are the factory's,
    not the operator's."""
    from factory.workgraph.worktree import SALVAGE_AUTHOR_EMAIL, SALVAGE_AUTHOR_NAME

    write_control(node_home)

    await adapter.run_attempt(attempt(), factory_root=factory_root)

    gitconfig = (node_home / ".gitconfig").read_text(encoding="utf-8")
    assert SALVAGE_AUTHOR_NAME in gitconfig
    assert SALVAGE_AUTHOR_EMAIL in gitconfig


# --- US1-S4: cleartext reasoning CoT does not misclassify (FR-007) --------------


async def test_cleartext_reasoning_near_the_output_does_not_misclassify(
    adapter: Any,
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    node_home: Path,
) -> None:
    """US1-S4 / FR-007 / trap 1: the ollama upstream returns chain-of-thought in
    cleartext (P1 measured; re-measured 2026-09-08 — interleaved into the plain
    exec stream on stderr). A successful run whose output carries reasoning
    text is COMPLETED; reasoning text alone is neither a success signal the
    classifier reads nor a refusal marker it can match."""
    reasoning_line = (
        'The user just wants the word "ok". No tool calls needed. '
        'Final answer: "ok".'
    )
    write_control(node_home, stdout=reasoning_line)

    result = await adapter.run_attempt(attempt(), factory_root=factory_root)

    assert result.termination == Termination.COMPLETED


async def test_a_refusal_is_never_read_from_reasoning_text(
    adapter: Any,
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    node_home: Path,
) -> None:
    """US1-S4, the refusal half: reasoning text that *resembles* an error or a
    refusal must not defeat the structural classification — a non-zero exit
    with a turn behind it is AGENT_ERROR whatever the model mused about."""
    write_control(
        node_home,
        exit_code=1,
        stdout='reasoning: the request failed with "unexpected status 401 '
        'Unauthorized" — or did it? just reasoning here.',
    )

    result = await adapter.run_attempt(attempt(), factory_root=factory_root)

    assert result.termination == Termination.AGENT_ERROR


# --- the turn probe (FR-007, trap 1) --------------------------------------------


async def test_a_codex_run_that_wrote_its_rollout_took_a_turn(
    adapter: Any,
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    node_home: Path,
) -> None:
    """The turn-happened probe, as Codex writes it: a rollout file under the
    seeded CODEX_HOME — which the CLI finds there without the factory having
    supplied an id (trap 4, measured). A failed run with a rollout behind it is
    the story's failure (AGENT_ERROR), not the environment's."""
    write_control(node_home, exit_code=1, write_rollout=True)

    result = await adapter.run_attempt(attempt(), factory_root=factory_root)

    assert result.termination == Termination.AGENT_ERROR


async def test_a_codex_run_that_wrote_no_rollout_is_pre_agent(
    adapter: Any,
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    node_home: Path,
) -> None:
    """A non-zero exit with no rollout file behind it produced no token — the
    pre-agent class (095-US1), now for Codex."""
    write_control(node_home, exit_code=1, write_rollout=False)

    result = await adapter.run_attempt(attempt(), factory_root=factory_root)

    assert result.termination == Termination.PRE_AGENT_FAILURE


# --- archive (FR-007 evidence) ---------------------------------------------------


async def test_the_attempt_directory_holds_the_log_and_the_rollout(
    adapter: Any,
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    node_home: Path,
) -> None:
    """Evidence survives the completed path for Codex as for Claude: the
    streamed log, and the rollout file the CLI wrote under CODEX_HOME."""
    write_control(node_home)

    result = await adapter.run_attempt(attempt(), factory_root=factory_root)

    assert result.termination == Termination.COMPLETED
    names = {p.name for p in archive_dir(factory_root).iterdir()}
    assert STDOUT_LOG_NAME in names
    assert BANNER in stdout_log(factory_root)
    rollouts = list(archive_dir(factory_root).glob("rollout-*.jsonl"))
    assert rollouts, "the rollout file was not archived beside the log"


async def test_the_rollout_never_lands_inside_the_worktree(
    adapter: Any,
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    node_home: Path,
) -> None:
    """FR-007 for Codex: the archive lives under the worker host's `.factory/`,
    never inside the tree salvage would commit."""
    write_control(node_home)

    result = await adapter.run_attempt(attempt(), factory_root=factory_root)

    archive = Path(result.transcript_path).resolve()
    assert not archive.is_relative_to(worktree.resolve())


# --- the refusal marker, on the measured stream (FR-004, FR-005 seam) -----------


async def test_a_refused_codex_run_is_visible_in_the_archived_log(
    adapter: Any,
    attempt: Callable[..., AttemptContext],
    worktree: Path,
    factory_root: Path,
    node_home: Path,
) -> None:
    """FR-004's plain-text promise, for the second CLI: the measured refusal —
    stderr, exit 1 (070's lesson inverted) — lands in the combined `stdout.log`
    the scanner reads, so the classifier can see it on the same stream either
    way. No `--json` is passed (US1-S2's other half already pins argv)."""
    write_control(node_home, exit_code=1, stderr=REFUSAL_MARKER)

    result = await adapter.run_attempt(attempt(), factory_root=factory_root)

    assert result.termination == Termination.AGENT_ERROR
    assert REFUSAL_MARKER in stdout_log(factory_root)


async def test_an_unresolvable_codex_agent_is_refused_at_the_seam() -> None:
    """Constitution IX at the registry: a name that is not in `_ADAPTERS`
    still refuses, naming the known list — registering codex does not loosen
    the seam."""
    with pytest.raises(AdapterError) as excinfo:
        adapter_for("opencode")
    assert "opencode" in str(excinfo.value)
    assert "codex" in str(excinfo.value)


# --- the env contract, shared-policy half ----------------------------------------


def test_attempt_env_carries_the_gateway_names_for_a_codex_context(
    attempt: Callable[..., AttemptContext],
    node_home: Path,
) -> None:
    """`attempt_env` builds the shared base — proxy URL and key for a gateway
    route under the Claude names — and the Codex adapter's `_provider_env` is
    what renames the credential pair for its CLI. The Codex names arrive via
    the seam; the Claude variable is not in the child env a Codex launch gets."""
    env = attempt_env(attempt())
    assert env["ANTHROPIC_BASE_URL"] == PROXY_URL
    assert env["ANTHROPIC_AUTH_TOKEN"] == VIRTUAL_KEY
    assert env["HOME"] == str(node_home)