"""114-US2: the cheap tier notices when the expensive one breaks.

`tests/test_114_us1_smoke_onboards.py` fixed the instance — the live-epic
smoke's scratch manifest declared a runtime the loader refuses, and twelve days
of green suites said nothing because the only test that read that manifest
needed a proxy, a `claude` binary and a Temporal server to run. This module is
what stops the class: for every live module that hand-authors a target
repository, the default `uv run pytest -q` builds that repository through the
module's *own* builder, runs the real onboarding over it, and fails by name when
something would refuse it. No credentials, no network, no model time — the
entire reason the defect survived is that nobody had written the two-second
version of the ten-minute test.

Three things here are deliberately derived rather than restated, because a
fixture that agrees with the code by coincidence is the defect this story exists
to end:

- the repository comes from the live module's own `build_scratch_repo`, so a
  second copy of the manifest cannot go green while the real one rots;
- `_is_landing_only_check` is imported from `factory.workgraph.workflow`, so the
  filter follows the day a fifth landing check is added instead of drifting;
- whether that filter applies at all is read off the `EpicInput` the live
  module's own `start` constructs, not asserted here as a belief about it.

And the covered set is not enumerated by hand alone: `test_the_guard_demands_
coverage_of_every_hand_authored_manifest` reads every `tests/test_live_*.py`
looking for a literal in its own source that parses as a repository manifest,
and turns red for any such module that this file does not cover. A module whose
manifest is *generated* — `tests/test_live_onramp.py` gets one from
`ergane init` and loads it with the real loader — is outside the rule and is
proven to be outside it below: writer and reader are the same code there, so it
cannot drift the way a literal can, and `init --wire` needs a real forge, so it
could not be built offline anyway.

Nothing in this module reads the environment or carries a marker, and
`test_the_check_carries_no_environment_guard` holds it to that. A check that
skips under the same conditions as the test it guards is not a guard.

Verification evidence (constitution VIII; US2-S1, US2-S3, US2-S4, SC-002)
--------------------------------------------------------------------------

**It runs with nothing loaded at all** (US2-S1, FR-004). Not the four variables
the tier needs — the whole environment, emptied to `HOME` and `PATH`: no
`LITELLM_PROXY_URL`, no `LITELLM_MASTER_KEY`, no `TEMPORAL_ADDRESS`, no
`TEMPORAL_NAMESPACE`, no `GH_TOKEN`, no server answering anywhere.

.. code-block:: text

    $ env -i HOME="$HOME" PATH="$PATH" .venv/bin/python -c \
        "import os; print(sorted(os.environ))"
    ['HOME', 'LC_CTYPE', 'PATH']

    $ env -i HOME="$HOME" PATH="$PATH" .venv/bin/python -m pytest \
        tests/test_114_us2_fixtures_onboard.py -q -p no:cacheprovider
    ..........
    10 passed, 1 warning in 0.49s

**It goes red on the defect it was written for** (US2-S4, FR-006). The same run,
with `manifest_source`'s runtime in `tests/test_live_epic.py` reverted to the
value `011-agent-sandbox` refused on 2026-08-15, and restored afterwards:

.. code-block:: text

    E  AssertionError: the scratch repository test_live_epic.py dispatches
       against does not onboard, so every epic built on it dies at the
       onboarding gate before a virtual key is issued
       (`factory/workgraph/workflow.py:1098`):
    E    [FAIL] factory_yaml: manifest failed to load: /tmp/.../factory.yaml:
         [runtime] declares `runtime: 'python:3.11-bookworm'`; the supported
         backend is `bwrap`

    FAILED ...::test_the_check_runs_with_no_live_environment
    FAILED ...::test_every_covered_live_module_s_repository_onboards[test_live_epic.py]
    FAILED ...::test_the_filter_is_applied_where_the_module_dispatches_halting[...]
    FAILED ...::test_the_check_fails_when_the_smoke_s_runtime_is_reverted
    4 failed, 6 passed, 1 warning in 0.54s

Both halves of what an operator needs are in the message: the runtime the
manifest declares, and the backend the loader supports.

**The covered and discovered sets** (US2-S3, FR-007), printed from the guard's
own functions — `True` is "hand-authors a manifest of its own":

.. code-block:: text

    covered:   test_live_epic.py  builder=tests.test_live_epic.build_scratch_repo
    discovered (tests/test_live_*.py):
      test_live_capacity.py    False
      test_live_epic.py        True
      test_live_judge.py       False
      test_live_merge.py       False
      test_live_notify.py      False
      test_live_onramp.py      False     <- generated by `ergane init`, not read
      test_live_proxy.py       False        as a literal; outside the rule
    uncovered: []

And the guard observed failing, with a fourth live module that hand-authors a
manifest dropped into `tests/` and then removed — the vacuous-sweep check that
`uncovered: []` above is a fact about the tier and not about the discovery:

.. code-block:: text

    E  AssertionError: these live modules hand-author a repository manifest and
       nothing cheap ever reads it:
    E      test_live_fourth.py
    E    Add each to test_114_us2_fixtures_onboard.py's COVERED_LIVE_MODULES.
    FAILED ...::test_the_guard_demands_coverage_of_every_hand_authored_manifest
    1 failed, 9 passed, 1 warning in 1.21s

**Full suite, before and after** — the ten tests here, and nothing else moved:

.. code-block:: text

    $ uv run pytest -q --ignore=tests/test_114_us2_fixtures_onboard.py
    5092 passed, 57 skipped, 7 warnings in 338.72s (0:05:38)

    $ uv run pytest -q
    5102 passed, 57 skipped, 6 warnings in 333.99s (0:05:33)

The skip count is unchanged, which is the whole point: these ten are not in the
tier they watch, so the default `uv run pytest -q` now fails on the day a live
module's repository stops being dispatchable, rather than twelve days later at
the next live dispatch.
"""

from __future__ import annotations

import ast
import asyncio
import os
import re
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable, Iterator

import pytest
import yaml

from factory.activities.merge_activities import _forge, onboard_target_repo
from factory.mergequeue.models import Finding
from factory.verify.factory_yaml import SUPPORTED_BACKENDS, resolve_manifest_path
from factory.workgraph import workflow as workflow_module
from factory.workgraph.workflow import _is_landing_only_check

from tests import test_live_epic as smoke

#: The environment the live tier needs and this module must not. Named here so
#: US2-S1's test can empty it and so a reader can see, in one place, exactly
#: which absences this check is claimed to survive.
LIVE_ENVIRONMENT = (
    "LITELLM_PROXY_URL",
    "LITELLM_MASTER_KEY",
    "TEMPORAL_ADDRESS",
    "TEMPORAL_NAMESPACE",
)

#: The runtime `011-agent-sandbox` stopped accepting on 2026-08-15, and which
#: the smoke's manifest went on declaring until US1. Written here as a literal
#: on purpose: it is the defect's value, not the code's, and a guard never
#: observed failing on the defect it was written for is a guard nobody has
#: reason to trust (US2-S4).
REFUSED_RUNTIME = "python:3.11-bookworm"


# --- the live modules this check covers ---------------------------------------


class _CapturingClient:
    """A Temporal client that records the dispatch instead of sending it.

    How a live module's dispatch mode is *read* rather than assumed: its own
    `start` is called with this in place of a client, and the `EpicInput` it
    constructs is the answer to whether the landing-only filter applies.
    """

    def __init__(self) -> None:
        self.epic_input: Any = None

    async def start_workflow(
        self, workflow: Any, epic_input: Any, /, **kwargs: Any
    ) -> Any:
        self.epic_input = epic_input
        return object()  # the handle; nothing here reads it


def smoke_dispatch(root: Path) -> Any:
    """The `EpicInput` `tests/test_live_epic.py` would dispatch, captured not sent.

    `start` only passes its config and workspace through to the client, so both
    address nothing that has to exist: no proxy is reached, no server is
    contacted and no path is written.
    """
    client = _CapturingClient()
    epic_id = "live-epic-offline"
    config = smoke.LiveConfig(
        proxy_url="http://127.0.0.1:1",
        master_key="not-a-key",
        model_alias="not-an-alias",
        address="127.0.0.1:1",
        namespace="ergane",
        timeout_s=1,
    )
    workspace = smoke.Workspace(
        epic_id=epic_id,
        target_repo=root / "target-repo",
        specs_root=root / "specs",
        spec_dir=root / "specs" / epic_id,
        factory_root=root / ".factory",
        ledger_path=root / ".factory" / "ledger.db",
        verification_db=root / ".factory" / "verification.db",
        task_queue=f"workgraph-{epic_id}",
    )
    asyncio.run(smoke.start(client, config, workspace, object()))
    return client.epic_input


@dataclass(frozen=True)
class CoveredLiveModule:
    """One live module, and the two things this check needs from it.

    Both are the module's own code rather than a description of it: the builder
    is the function the live run itself calls, and `dispatched_epic_input`
    captures the dispatch the live run itself would make.
    """

    filename: str
    build_scratch_repo: Callable[[Path], Path]
    dispatched_epic_input: Callable[[Path], Any]


#: The live-epic smoke's own file name, read off the module rather than spelled
#: again: the tests below name it in their failure messages, and a rename that
#: left this behind would report a file nobody could go and open.
SMOKE_FILENAME = Path(smoke.__file__).name


COVERED_LIVE_MODULES = (
    CoveredLiveModule(
        filename=SMOKE_FILENAME,
        build_scratch_repo=smoke.build_scratch_repo,
        dispatched_epic_input=smoke_dispatch,
    ),
)

COVERED_FILENAMES = frozenset(module.filename for module in COVERED_LIVE_MODULES)


# --- the check ----------------------------------------------------------------


def onboarding_findings(repo: Path) -> tuple[Finding, ...]:
    """Every finding the real onboarding produces about `repo`, offline.

    `onboard_target_repo` is the same function the dispatch gate's activity
    calls (`factory/activities/merge_activities.py:612`, `:758`); the forge is
    resolved against the clone exactly as `validate_target_repo` resolves it.
    Nothing here needs a proxy, an agent, a Temporal server or a network: the
    manifest is read off disk and the forge refuses a repository it cannot read
    locally.
    """
    profile = onboard_target_repo(_forge(repo_path=str(repo)), str(repo))
    return profile.findings


def blocking_findings(repo: Path, *, halting: bool) -> list[Finding]:
    """What onboarding would refuse `repo` for, as the dispatch gate reads it."""
    return surviving_failures(onboarding_findings(repo), halting=halting)


def surviving_failures(
    findings: tuple[Finding, ...], *, halting: bool
) -> list[Finding]:
    """The failures that still refuse a repository, filtered as the gate filters.

    The same two lines as `EpicWorkflow._onboard`
    (`factory/workgraph/workflow.py:1104-1127`): every finding that did not
    pass, less the landing-only ones when the epic will never land. The
    predicate is imported, never restated — a second copy of
    `_LANDING_ONLY_CHECKS` here is two lists that drift while both stay green.
    """
    failed = [finding for finding in findings if not finding.passed]
    if halting:
        failed = [
            finding for finding in failed if not _is_landing_only_check(finding.check)
        ]
    return failed


def render_findings(findings: list[Finding]) -> str:
    """The findings, one per line, marked as the onboarding gate marks them."""
    return "\n".join(
        f"  [{finding.mark}] {finding.check}: {finding.detail}" for finding in findings
    )


def check_repository_onboards(
    module_name: str, repo: Path, *, halting: bool
) -> tuple[Finding, ...]:
    """Raise unless `repo` would clear the onboarding gate; return what was read.

    The message names every survivor with its check and its detail (FR-006):
    `assert profile.passed` tells a reader that something is wrong and nothing
    about which of two independent blockers to go and fix.

    Returns every finding onboarding produced, so a caller can prove this did
    the work rather than declining to.
    """
    findings = onboarding_findings(repo)
    survivors = surviving_failures(findings, halting=halting)
    if survivors:
        raise AssertionError(
            f"the scratch repository {module_name} dispatches against does not "
            "onboard, so every epic built on it dies at the onboarding gate "
            "before a virtual key is issued "
            "(`factory/workgraph/workflow.py:1098`)"
            + ("" if halting else ", and this module does not dispatch halting")
            + ":\n"
            + render_findings(survivors)
        )
    return findings


# --- the coverage guard -------------------------------------------------------

#: The keys a document must carry to be a repository manifest rather than some
#: other YAML. Three, because the loader refuses a document missing any of them
#: (`factory/verify/factory_yaml.py:194-198`), so nothing that lacks one could
#: be the manifest a live module is dispatching against.
MANIFEST_KEYS = frozenset({"version", "runtime", "gates"})

#: What an f-string's interpolations stand in as while the literal around them
#: is read: a plain scalar, so `runtime: {SUPPORTED_BACKENDS[0]}` is still a
#: mapping entry and the document still parses.
MANIFEST_PLACEHOLDER = "interpolated"

#: The live tier's modules, by the name they are collected under.
LIVE_MODULE_GLOB = "test_live_*.py"

TESTS_DIR = Path(__file__).resolve().parent


def discover_live_modules() -> list[Path]:
    """Every `tests/test_live_*.py`, found rather than listed."""
    return sorted(TESTS_DIR.glob(LIVE_MODULE_GLOB))


def hand_authors_manifest(module_path: Path) -> bool:
    """Whether this module writes a repository manifest from a literal of its own.

    Read off the module's syntax, not its imports: a string or f-string that
    parses as a document carrying every `MANIFEST_KEYS` key is a manifest
    written by hand, and it is the shape that can drift away from the loader
    while the suite stays green. Docstrings are excluded — prose about a
    manifest is not a manifest — and a *generated* manifest is invisible to
    this by construction, which is exactly the boundary FR-007 draws.
    """
    tree = ast.parse(module_path.read_text(encoding="utf-8"))
    return any(
        parses_as_manifest(text) for text in authored_literals(tree)
    )


def uncovered_live_modules(module_paths: list[Path]) -> list[Path]:
    """The modules that hand-author a manifest and are not covered above."""
    return [
        path
        for path in module_paths
        if path.name not in COVERED_FILENAMES and hand_authors_manifest(path)
    ]


def authored_literals(tree: ast.Module) -> Iterator[str]:
    """Every string this module writes out, docstrings excluded.

    An f-string counts, with each interpolation standing in as a scalar: the
    manifest a live module writes is nearly always one
    (`manifest_source`, `tests/test_live_epic.py:299`), and a rule that could
    not see through interpolation would see no manifests at all.
    """
    prose = {id(node) for node in docstring_nodes(tree)}
    for node in ast.walk(tree):
        if isinstance(node, ast.JoinedStr):
            yield "".join(
                part.value
                if isinstance(part, ast.Constant) and isinstance(part.value, str)
                else MANIFEST_PLACEHOLDER
                for part in node.values
            )
        elif (
            isinstance(node, ast.Constant)
            and isinstance(node.value, str)
            and id(node) not in prose
        ):
            yield node.value


def parses_as_manifest(text: str) -> bool:
    """Whether `text` is a repository manifest rather than some other string."""
    try:
        document = yaml.safe_load(text)
    except (yaml.YAMLError, ValueError):
        return False
    return isinstance(document, dict) and MANIFEST_KEYS <= {
        str(key) for key in document
    }


def docstring_nodes(tree: ast.Module) -> list[ast.Constant]:
    """The string literals that are documentation: one per module, class and def."""
    found: list[ast.Constant] = []
    for node in ast.walk(tree):
        if not isinstance(
            node, (ast.Module, ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)
        ):
            continue
        first = node.body[0] if node.body else None
        if (
            isinstance(first, ast.Expr)
            and isinstance(first.value, ast.Constant)
            and isinstance(first.value.value, str)
        ):
            found.append(first.value)
    return found


def code_without_prose(source: str) -> str:
    """`source` with every docstring and comment gone, so a scan reads only code.

    Round-tripped through `ast.unparse`, which drops comments by construction —
    so a scan over the result reads what this module *does* and never what it
    says about what it does.
    """
    tree = ast.parse(source)
    for node in ast.walk(tree):
        if not isinstance(
            node, (ast.Module, ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)
        ):
            continue
        first = node.body[0] if node.body else None
        if (
            isinstance(first, ast.Expr)
            and isinstance(first.value, ast.Constant)
            and isinstance(first.value.value, str)
        ):
            node.body = node.body[1:] or [ast.Pass()]
    return ast.unparse(tree)


# --- US2-S1: it runs when nothing else in the tier does -----------------------


def test_the_check_runs_with_no_live_environment(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """US2-S1, FR-004: no proxy, no key, no Temporal server — and it executes.

    A check that skips under the same conditions as the test it guards is not a
    guard (plan T4), so this empties the live tier's whole environment and then
    insists on evidence that the work happened: onboarding is asked about every
    covered module's repository and returns findings about each.
    """
    for name in LIVE_ENVIRONMENT:
        monkeypatch.delenv(name, raising=False)
    for name in LIVE_ENVIRONMENT:
        assert name not in os.environ, f"{name} survived being emptied"

    examined: dict[str, tuple[Finding, ...]] = {}
    for module in COVERED_LIVE_MODULES:
        root = tmp_path / module.filename
        repo = module.build_scratch_repo(root / "target-repo")
        halting = module.dispatched_epic_input(root).halt_after_pass
        try:
            examined[module.filename] = check_repository_onboards(
                module.filename, repo, halting=halting
            )
        except pytest.skip.Exception as skipped:
            pytest.fail(
                f"the check declined to run over {module.filename} with the live "
                f"tier's environment emptied, which is precisely the condition it "
                f"exists to cover: {skipped}"
            )

    assert set(examined) == COVERED_FILENAMES
    for filename, findings in examined.items():
        assert findings, (
            f"onboarding returned no findings at all about {filename}'s scratch "
            "repository, so this check passed without reading anything"
        )


def test_the_check_carries_no_environment_guard() -> None:
    """FR-004, plan T4: this module cannot become a second invisible test.

    Read off its own syntax rather than trusted: no call that skips, no marker
    that auto-skips, no module-level `pytestmark`. If any of the three ever
    appears, this module joins the tier it is supposed to be watching from
    outside, and the story has produced nothing.
    """
    tree = ast.parse(Path(__file__).read_text(encoding="utf-8"))

    skipping_calls = [
        node
        for node in ast.walk(tree)
        if isinstance(node, ast.Call)
        and isinstance(node.func, ast.Attribute)
        and node.func.attr in {"skip", "importorskip", "xfail"}
    ]
    assert not skipping_calls, (
        "this module calls "
        + ", ".join(f"`.{node.func.attr}()`" for node in skipping_calls)  # type: ignore[union-attr]
        + " — a check that can decline to run is not a guard"
    )

    markers = [
        node.attr
        for item in ast.walk(tree)
        if isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))
        for decorator in item.decorator_list
        for node in ast.walk(decorator)
        if isinstance(node, ast.Attribute)
        and (node.attr.startswith("live_") or node.attr in {"skip", "skipif"})
    ]
    assert not markers, (
        f"this module carries the markers {sorted(set(markers))}, which auto-skip "
        "under exactly the conditions that hid the defect it was written for"
    )

    assigned = {
        target.id
        for node in tree.body
        if isinstance(node, ast.Assign)
        for target in node.targets
        if isinstance(target, ast.Name)
    }
    assert "pytestmark" not in assigned, (
        "this module sets a module-level `pytestmark`, which applies a marker to "
        "every test in it"
    )


# --- US2-S2: the real onboarding, the real predicate, named survivors ---------


@pytest.mark.parametrize(
    "module", COVERED_LIVE_MODULES, ids=lambda module: module.filename
)
def test_every_covered_live_module_s_repository_onboards(
    module: CoveredLiveModule, tmp_path: Path
) -> None:
    """US2-S2, FR-004/005/006: build it, onboard it, and name what survives.

    This is the two-second version of the ten-minute test: the same builder the
    live run uses, the same `onboard_target_repo` the dispatch gate calls, and
    the same landing-only filter the workflow applies — with whether to apply it
    read off the `EpicInput` the module's own `start` constructs.
    """
    root = tmp_path / module.filename
    repo = module.build_scratch_repo(root / "target-repo")
    halting = module.dispatched_epic_input(root).halt_after_pass
    check_repository_onboards(module.filename, repo, halting=halting)


@pytest.mark.parametrize(
    "module", COVERED_LIVE_MODULES, ids=lambda module: module.filename
)
def test_the_filter_is_applied_where_the_module_dispatches_halting(
    module: CoveredLiveModule, tmp_path: Path
) -> None:
    """FR-005: the filter is applied when, and only when, the epic will not land.

    Two ways this check could quietly stop proving anything, both closed here.
    It could forgive landing findings for a module that dispatches normally —
    so the flag is read from the module's own dispatch. And it could be
    vacuously green because onboarding refused nothing at all — so the
    unfiltered profile is asserted to still carry failures, every one of them
    landing-only, for a repository whose dispatch halts.
    """
    root = tmp_path / module.filename
    repo = module.build_scratch_repo(root / "target-repo")
    halting = module.dispatched_epic_input(root).halt_after_pass

    unfiltered = blocking_findings(repo, halting=False)
    if not halting:
        assert not unfiltered, (
            f"{module.filename} dispatches without halting, so nothing about its "
            "repository may be forgiven:\n" + render_findings(unfiltered)
        )
        return

    assert unfiltered, (
        f"onboarding now refuses nothing about {module.filename}'s scratch "
        "repository, so the landing-only filter proves nothing here any more"
    )
    assert all(_is_landing_only_check(finding.check) for finding in unfiltered), (
        f"onboarding refuses {module.filename}'s repository for something the "
        "halting dispatch does not forgive:\n" + render_findings(unfiltered)
    )


def test_the_landing_only_predicate_is_imported_not_restated() -> None:
    """FR-005, plan T3: one list, in the workflow, and this module reads it.

    Identity first — the name this module filters with is the workflow's own
    function object, not a lookalike — and then the thing identity cannot see:
    that no check name or prefix from `_LANDING_ONLY_CHECKS` has been copied
    into this module's code. Restating them is faster and is exactly what
    leaves two lists that drift while both stay green; this repository has the
    receipts for that failure mode three times over in `tests/page_holds_true.py`.
    """
    assert _is_landing_only_check is workflow_module._is_landing_only_check

    code = code_without_prose(Path(__file__).read_text(encoding="utf-8"))
    restated = sorted(
        name
        for name in (
            *workflow_module._LANDING_ONLY_CHECKS,
            *workflow_module._LANDING_ONLY_CHECK_PREFIXES,
        )
        if name in code
    )
    assert not restated, (
        f"this module writes the landing-only check names {restated} into its own "
        "code; it must ask `_is_landing_only_check`, so that the day a fifth "
        "landing check is added the filter follows it"
    )


def test_a_broken_manifest_is_reported_by_name(tmp_path: Path) -> None:
    """US2-S2, FR-006: the failure names the check and the detail, not a boolean.

    Driven against a repository whose manifest declares a backend that does not
    exist, so what the message must carry is unambiguous: the failing check's
    name, the value the manifest declares, and the backend the loader supports.
    """
    repo = smoke.build_scratch_repo(tmp_path / "target-repo")
    declare_runtime(repo, "not-a-backend")

    with pytest.raises(AssertionError) as raised:
        check_repository_onboards(SMOKE_FILENAME, repo, halting=True)

    message = str(raised.value)
    assert "factory_yaml" in message, message
    assert "not-a-backend" in message, message
    assert SUPPORTED_BACKENDS[0] in message, message


# --- US2-S4: observed failing on the defect it was written for ----------------


def test_the_check_fails_when_the_smoke_s_runtime_is_reverted(tmp_path: Path) -> None:
    """US2-S4, FR-006: put the refused runtime back, and this goes red by name.

    A copy of the corrected repository, reverted in the copy alone, so the
    fixture US1 fixed is left exactly as it is and this still observes the
    guard failing on the defect that produced the story. Both halves of the
    message matter: the runtime the manifest declares is what to change, and
    the supported backend is what to change it to.
    """
    corrected = smoke.build_scratch_repo(tmp_path / "target-repo")
    check_repository_onboards(SMOKE_FILENAME, corrected, halting=True)

    reverted = tmp_path / "reverted-repo"
    shutil.copytree(corrected, reverted)
    declare_runtime(reverted, REFUSED_RUNTIME)

    with pytest.raises(AssertionError) as raised:
        check_repository_onboards(SMOKE_FILENAME, reverted, halting=True)

    message = str(raised.value)
    assert REFUSED_RUNTIME in message, message
    assert SUPPORTED_BACKENDS[0] in message, message


# --- US2-S3: the covered set is not enumerated by hand alone ------------------


def test_the_guard_demands_coverage_of_every_hand_authored_manifest() -> None:
    """US2-S3, FR-007: every live module that writes its own manifest is covered.

    The failure this exists to prevent is a fourth live module arriving with a
    hand-written manifest while the suite stays green, so the set it judges is
    discovered rather than listed, and the covered names are checked to still
    name modules that exist.
    """
    discovered = discover_live_modules()
    assert discovered, (
        f"no {LIVE_MODULE_GLOB} module was found under {TESTS_DIR}; a guard whose "
        "discovery finds nothing reports zero uncovered modules forever"
    )
    names = {path.name for path in discovered}
    assert COVERED_FILENAMES <= names, (
        f"this module claims to cover {sorted(COVERED_FILENAMES - names)}, which "
        f"no longer exists under {TESTS_DIR}"
    )

    unseen = sorted(
        filename
        for filename in COVERED_FILENAMES
        if not hand_authors_manifest(TESTS_DIR / filename)
    )
    assert not unseen, (
        f"the guard reads {unseen} as writing no manifest of its own, while this "
        "module covers it for doing exactly that — either the module stopped and "
        "its coverage should go, or the guard has stopped seeing manifests and is "
        "now reporting zero uncovered modules about nothing"
    )

    uncovered = uncovered_live_modules(discovered)
    assert not uncovered, (
        "these live modules hand-author a repository manifest and nothing cheap "
        "ever reads it:\n"
        + "\n".join(f"  {path.name}" for path in uncovered)
        + f"\nAdd each to {Path(__file__).name}'s COVERED_LIVE_MODULES."
    )


def test_the_guard_fails_on_a_module_that_writes_its_own_manifest(
    tmp_path: Path,
) -> None:
    """US2-S3, plan T5: proven by watching the guard turn red, not by trusting it.

    A throwaway module that hand-authors a manifest is added to the discovered
    set, and the guard must name it. Without this, "zero uncovered modules" is a
    claim about the guard's discovery and not about the tier — the vacuous sweep
    this repository has shipped before.
    """
    throwaway = tmp_path / "test_live_throwaway.py"
    throwaway.write_text(throwaway_module_source(), encoding="utf-8")

    assert hand_authors_manifest(throwaway), (
        "the guard does not see a manifest written as a literal, so it would not "
        "see one in a real live module either"
    )
    uncovered = uncovered_live_modules([*discover_live_modules(), throwaway])
    assert throwaway in uncovered, (
        "the guard passed a live module that hand-authors a manifest and is not "
        f"covered; it reported {[path.name for path in uncovered]}"
    )

    silent = tmp_path / "test_live_silent.py"
    silent.write_text(
        '"""A live module that builds no repository at all."""\n', encoding="utf-8"
    )
    assert silent not in uncovered_live_modules([silent]), (
        "the guard demands coverage of a live module that writes no manifest, so "
        "it is failing on the glob rather than on the hazard"
    )


def test_the_guard_does_not_demand_the_generated_manifest() -> None:
    """US2-S3, FR-007: a manifest `ergane init` writes is outside the rule.

    `tests/test_live_onramp.py` ends up with a manifest, but it is generated by
    `ergane init --wire` and then read by the real loader
    (`tests/test_live_onramp.py:687-694`): writer and reader are the same code,
    so it cannot drift the way a literal can, and `--wire` needs a real forge,
    so its repository cannot be built offline at all. A guard that demanded it
    would demand something impossible and be relaxed within the hour.
    """
    onramp = TESTS_DIR / "test_live_onramp.py"
    assert onramp.is_file(), f"{onramp} has been renamed; this test names it"

    assert not hand_authors_manifest(onramp), (
        f"{onramp.name} is read as hand-authoring a manifest, so the guard now "
        "demands offline coverage of a repository only `ergane init --wire` can "
        "build"
    )
    assert onramp not in uncovered_live_modules(discover_live_modules())


# --- helpers used by the tests above ------------------------------------------


def declare_runtime(repo: Path, runtime: str) -> None:
    """Rewrite the manifest's `runtime:` line in place, and prove it changed."""
    manifest, _name = resolve_manifest_path(repo)
    source = manifest.read_text(encoding="utf-8")
    rewritten = re.sub(r"(?m)^runtime:.*$", f"runtime: {runtime}", source)
    assert rewritten != source, (
        f"{manifest} declares no `runtime:` line to rewrite:\n{source}"
    )
    manifest.write_text(rewritten, encoding="utf-8")


def throwaway_module_source() -> str:
    """A live-looking module that hand-authors a manifest, for the guard's test.

    The backend it declares is interpolated for the same reason `manifest_source`
    interpolates it: no file in this repository should carry a supported backend
    name as a literal, not even a fixture that exists to be thrown away.
    """
    manifest = "\n".join(
        (
            "version: 1",
            f"runtime: {SUPPORTED_BACKENDS[0]}",
            "",
            "gates:",
            '  test: "pytest -q"',
            "",
            "standards: STANDARDS.md",
        )
    )
    return (
        '"""A live module that writes its own manifest — the shape FR-007 names."""\n'
        "\n\n"
        "def build_scratch_repo(path):\n"
        f"    (path / 'factory.yaml').write_text({manifest!r}, encoding='utf-8')\n"
    )
